Repository vmware/terraform-provider-vsphere, pull requests merged in 2018-04, with the labels that each got.

#448 tests: Fix vApp ISO tests
  vendor/github.com/hashicorp/terraform/helper/pathorcontents/read.go
  vendor/github.com/terraform-providers/terraform-provider-template/LICENSE
  vendor/github.com/terraform-providers/terraform-provider-template/template/datasource_cloudinit_config.go
  vendor/github.com/terraform-providers/terraform-provider-template/template/datasource_template_file.go
  vendor/github.com/terraform-providers/terraform-provider-template/template/provider.go
  vendor/github.com/terraform-providers/terraform-provider-template/template/resource_template_dir.go
  vendor/vendor.json
  vsphere/provider_test.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: bug

#447 r/virtual_machine: Datastore cluster support
  tf-vsphere-devrc.mk.example
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_map.go
  vendor/github.com/hashicorp/terraform/helper/schema/provider.go
  vendor/github.com/hashicorp/terraform/helper/schema/resource.go
  vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go
  vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go
  vendor/github.com/hashicorp/terraform/helper/schema/schema.go
  vendor/vendor.json
  vsphere/internal/helper/storagepod/storage_pod_helper.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: enhancement

#452 r/datastore_cluster: Change default SDRS automation level to manual
  vsphere/resource_vsphere_datastore_cluster.go
  website/docs/r/datastore_cluster.html.markdown
Labels: bug

#450 New resource: vsphere_storage_drs_vm_override
  vsphere/helper_test.go
  vsphere/internal/helper/structure/structure_helper.go
  vsphere/provider.go
  vsphere/resource_vsphere_storage_drs_vm_override.go
  vsphere/resource_vsphere_storage_drs_vm_override_test.go
  website/docs/r/storage_drs_vm_override.html.markdown
  website/vsphere.erb
Labels: enhancement, new-resource

#455 r/virtual_machine: Backings should never be added to disks w/SDRS
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: bug

#459 datastore.html sample code fix
  website/docs/d/datastore.html.markdown
Labels: documentation

#458 r/virtual_machine: Fix vApp ISO tests
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: bug

#460 r/virtual_machine: Remove clone config restriction for import/legacy
  vendor/github.com/hashicorp/terraform/config/config.go
  vendor/github.com/hashicorp/terraform/config/interpolate_funcs.go
  vendor/github.com/hashicorp/terraform/config/module/get.go
  vendor/github.com/hashicorp/terraform/config/module/inode.go
  vendor/github.com/hashicorp/terraform/config/module/storage.go
  vendor/github.com/hashicorp/terraform/config/module/validate_provider_alias.go
  vendor/github.com/hashicorp/terraform/helper/resource/id.go
  vendor/github.com/hashicorp/terraform/helper/resource/testing.go
  vendor/github.com/hashicorp/terraform/helper/resource/wait.go
  vendor/github.com/hashicorp/terraform/helper/schema/resource_diff.go
  vendor/github.com/hashicorp/terraform/helper/schema/schema.go
  vendor/github.com/hashicorp/terraform/helper/validation/validation.go
  vendor/github.com/hashicorp/terraform/httpclient/client.go
  vendor/github.com/hashicorp/terraform/httpclient/useragent.go
  vendor/github.com/hashicorp/terraform/plugin/discovery/find.go
  vendor/github.com/hashicorp/terraform/plugin/discovery/get.go
  vendor/github.com/hashicorp/terraform/registry/client.go
  vendor/github.com/hashicorp/terraform/registry/errors.go
  vendor/github.com/hashicorp/terraform/svchost/disco/disco.go
  vendor/github.com/hashicorp/terraform/terraform/context.go
  vendor/github.com/hashicorp/terraform/terraform/eval_apply.go
  vendor/github.com/hashicorp/terraform/terraform/eval_diff.go
  vendor/github.com/hashicorp/terraform/terraform/eval_validate.go
  vendor/github.com/hashicorp/terraform/terraform/graph_builder_apply.go
  vendor/github.com/hashicorp/terraform/terraform/interpolate.go
  vendor/github.com/hashicorp/terraform/terraform/module_dependencies.go
  vendor/github.com/hashicorp/terraform/terraform/node_local.go
  vendor/github.com/hashicorp/terraform/terraform/node_output.go
  vendor/github.com/hashicorp/terraform/terraform/node_resource_apply.go
  vendor/github.com/hashicorp/terraform/terraform/node_resource_refresh.go
  vendor/github.com/hashicorp/terraform/terraform/plan.go
  vendor/github.com/hashicorp/terraform/terraform/resource.go
  vendor/github.com/hashicorp/terraform/terraform/resource_provider_mock.go
  vendor/github.com/hashicorp/terraform/terraform/state.go
  vendor/github.com/hashicorp/terraform/terraform/transform_output.go
  vendor/github.com/hashicorp/terraform/terraform/transform_provider.go
  vendor/github.com/hashicorp/terraform/terraform/transform_reference.go
  vendor/github.com/hashicorp/terraform/terraform/transform_targets.go
  vendor/github.com/hashicorp/terraform/terraform/user_agent.go
  vendor/github.com/hashicorp/terraform/version/version.go
  vendor/github.com/mitchellh/copystructure/copystructure.go
  vendor/github.com/mitchellh/reflectwalk/location.go
  vendor/github.com/mitchellh/reflectwalk/location_string.go
  vendor/github.com/mitchellh/reflectwalk/reflectwalk.go
  vendor/vendor.json
  vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
  vsphere/internal/vmworkflow/virtual_machine_customize_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: enhancement

#463 d/virtual_machine: Nil check for empty VM configuration
  vsphere/data_source_vsphere_virtual_machine.go
Labels: bug, crash

#465 vendor: Update TF to @v0.11.7
  vendor/github.com/hashicorp/terraform/terraform/interpolate.go
  vendor/github.com/hashicorp/terraform/version/version.go
  vendor/vendor.json
Labels: dependencies

#467 r/virtual_machine: Roll back all VM post-clone config operations
  vsphere/resource_vsphere_virtual_machine.go
Labels: bug

#470 r/virtual_machine: Controllable routable network waiter behavior
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_migrate.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: enhancement

#474 r/virtual_machine: Allow vMotions to other clusters
  tf-vsphere-devrc.mk.example
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: bug

#475 r/virtual_machine: Restore ID availability to rollback functionality
  vsphere/resource_vsphere_virtual_machine.go
Labels: bug

#476 r/virtual_machine: Explicitly block cloning on standalone ESXi
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: bug

#481 r/virtual_machine: Split disk Diff
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: bug

#482 Fixing example code (documentation)
  website/docs/d/resource_pool.html.markdown
  website/docs/d/virtual_machine.html.markdown
Labels: documentation

#484 Minor grammar correction
  website/docs/r/virtual_machine.html.markdown
Labels: documentation

#485 r/virtual_machine: Add `firmware` attribute to VM data source
  vsphere/data_source_vsphere_virtual_machine.go
  vsphere/data_source_vsphere_virtual_machine_test.go
  website/docs/d/virtual_machine.html.markdown
Labels: enhancement

#487 r/compute_cluster: New resource
  tf-vsphere-devrc.mk.example
  vsphere/helper_test.go
  vsphere/internal/helper/clustercomputeresource/cluster_compute_resource_helper.go
  vsphere/internal/helper/computeresource/compute_resource_helper.go
  vsphere/internal/helper/folder/folder_helper.go
  vsphere/internal/helper/hostsystem/host_system_helper.go
  vsphere/internal/helper/structure/structure_helper.go
  vsphere/internal/helper/viapi/vim_helper.go
  vsphere/provider.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_test.go
  vsphere/resource_vsphere_datastore_cluster.go
  website/docs/r/compute_cluster.html.markdown
  website/vsphere.erb
Labels: enhancement, new-resource

#492 d/compute_cluster: New data source
  vsphere/data_source_vsphere_compute_cluster.go
  vsphere/data_source_vsphere_compute_cluster_test.go
  vsphere/provider.go
  website/docs/d/compute_cluster.html.markdown
  website/docs/d/resource_pool.html.markdown
  website/docs/r/virtual_machine.html.markdown
  website/vsphere.erb
Labels: enhancement, new-data-source
