Repository vmware/terraform-provider-vsphere, pull requests merged in 2018-03, with the labels that each got.

#418 Convert all acceptance tests to individual tests
  vsphere/data_source_vsphere_custom_attribute_test.go
  vsphere/data_source_vsphere_datacenter_test.go
  vsphere/data_source_vsphere_datastore_test.go
  vsphere/data_source_vsphere_distributed_virtual_switch_test.go
  vsphere/data_source_vsphere_host_test.go
  vsphere/data_source_vsphere_network_test.go
  vsphere/data_source_vsphere_resource_pool_test.go
  vsphere/data_source_vsphere_tag_category_test.go
  vsphere/data_source_vsphere_tag_test.go
  vsphere/data_source_vsphere_virtual_machine_test.go
  vsphere/data_source_vsphere_vmfs_disks_test.go
  vsphere/resource_vsphere_custom_attribute_test.go
  vsphere/resource_vsphere_datacenter_test.go
  vsphere/resource_vsphere_distributed_port_group_test.go
  vsphere/resource_vsphere_distributed_virtual_switch_test.go
  vsphere/resource_vsphere_file_test.go
  vsphere/resource_vsphere_folder_migrate_test.go
  vsphere/resource_vsphere_folder_test.go
  vsphere/resource_vsphere_host_port_group_test.go
  vsphere/resource_vsphere_host_virtual_switch_test.go
  vsphere/resource_vsphere_license_test.go
  vsphere/resource_vsphere_nas_datastore_test.go
  vsphere/resource_vsphere_tag_category_test.go
  vsphere/resource_vsphere_tag_test.go
  vsphere/resource_vsphere_virtual_machine_snapshot_test.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/resource_vsphere_vmfs_datastore_test.go
Labels: technical-debt

#422 provider: Add session persistence
  vendor/github.com/vmware/vic/LICENSE
  vendor/github.com/vmware/vic/pkg/vsphere/tags/rest_client.go
  vendor/vendor.json
  vsphere/config.go
  vsphere/config_test.go
  vsphere/provider.go
  website/docs/index.html.markdown
Labels: enhancement

#426 provider: Fix keys in configuration function, refactor stack
  vsphere/config.go
  vsphere/config_test.go
  vsphere/provider.go
Labels: bug, crash

#427 r/virtual_machine: Fix broken acceptance tests and CD drives
  vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: bug

#436 New resource: vsphere_datastore_cluster
  vsphere/helper_test.go
  vsphere/internal/helper/customattribute/custom_attributes_helper.go
  vsphere/internal/helper/folder/folder_helper.go
  vsphere/internal/helper/storagepod/storage_pod_helper.go
  vsphere/internal/helper/structure/structure_helper.go
  vsphere/provider.go
  vsphere/resource_vsphere_datastore_cluster.go
  vsphere/resource_vsphere_datastore_cluster_test.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/tags_helper.go
  website/docs/r/datastore_cluster.html.markdown
  website/vsphere.erb
Labels: enhancement, new-resource

#437 d/datastore_cluster: New data source
  vsphere/data_source_vsphere_datastore_cluster.go
  vsphere/data_source_vsphere_datastore_cluster_test.go
  vsphere/provider.go
  vsphere/resource_vsphere_datastore_cluster.go
  vsphere/resource_vsphere_datastore_cluster_test.go
  website/docs/d/datastore_cluster.html.markdown
  website/vsphere.erb
Labels: enhancement, new-data-source

#439 Add datastore cluster support to datastore resources
  vsphere/datastore_structure.go
  vsphere/datastore_summary_structure.go
  vsphere/internal/helper/folder/folder_helper.go
  vsphere/resource_vsphere_nas_datastore.go
  vsphere/resource_vsphere_nas_datastore_test.go
  vsphere/resource_vsphere_vmfs_datastore.go
  vsphere/resource_vsphere_vmfs_datastore_test.go
  website/docs/r/nas_datastore.html.markdown
  website/docs/r/vmfs_datastore.html.markdown
Labels: enhancement

#440 r/virtual_machine vApp ISO transport support
  vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go
  vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/virtual_machine_config_structure.go
  website/docs/r/virtual_machine.html.markdown
Labels: enhancement
