Repository vmware/terraform-provider-vsphere, pull requests merged in 2018-02, with the labels that each got.

#398 vendor: Update govmomi to bb8ff8d
  vendor/github.com/vmware/govmomi/CHANGELOG.md
  vendor/github.com/vmware/govmomi/CONTRIBUTORS
  vendor/github.com/vmware/govmomi/Makefile
  vendor/github.com/vmware/govmomi/README.md
  vendor/github.com/vmware/govmomi/event/manager.go
  vendor/github.com/vmware/govmomi/event/processor.go
  vendor/github.com/vmware/govmomi/find/finder.go
  vendor/github.com/vmware/govmomi/nfc/lease.go
  vendor/github.com/vmware/govmomi/nfc/lease_updater.go
  vendor/github.com/vmware/govmomi/object/cluster_compute_resource.go
  vendor/github.com/vmware/govmomi/object/common.go
  vendor/github.com/vmware/govmomi/object/compute_resource.go
  vendor/github.com/vmware/govmomi/object/datacenter.go
  vendor/github.com/vmware/govmomi/object/datastore.go
  vendor/github.com/vmware/govmomi/object/datastore_file.go
  vendor/github.com/vmware/govmomi/object/host_storage_system.go
  vendor/github.com/vmware/govmomi/object/types.go
  vendor/github.com/vmware/govmomi/object/virtual_disk_manager.go
  vendor/github.com/vmware/govmomi/object/virtual_disk_manager_internal.go
  vendor/github.com/vmware/govmomi/object/virtual_machine.go
  vendor/github.com/vmware/govmomi/property/collector.go
  vendor/github.com/vmware/govmomi/session/manager.go
  vendor/github.com/vmware/govmomi/vim25/progress/reader.go
  vendor/github.com/vmware/govmomi/vim25/soap/client.go
  vendor/github.com/vmware/govmomi/vim25/types/helpers.go
  vendor/github.com/vmware/govmomi/vim25/types/if.go
  vendor/github.com/vmware/govmomi/vim25/types/types.go
  vendor/vendor.json
  vsphere/resource_vsphere_file.go
  vsphere/virtual_machine_config_structure.go
Labels: bug, dependencies

#383 Add OVF deployment example
  examples/ovf-template/Makefile
  examples/ovf-template/README.md
  examples/ovf-template/scripts/build.sh
  examples/ovf-template/scripts/preload_vars.sh
  examples/ovf-template/scripts/template.sh
  examples/ovf-template/terraform/data_sources.tf
  examples/ovf-template/terraform/files/00-ens192.network.tpl
  examples/ovf-template/terraform/files/ovf-example.service.tpl
  examples/ovf-template/terraform/ignition.tf
  examples/ovf-template/terraform/provider.tf
  examples/ovf-template/terraform/terraform.tfvars.example
  examples/ovf-template/terraform/variables.tf
  examples/ovf-template/terraform/virtual_machines.tf
Labels: documentation

#390 Issue 348
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: enhancement

#405 r/virtual_machine: Address vCenter upgrade issues
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource_test.go
Labels: bug

#414 r/virtual_machine: Handle missing environment browser
  tf-vsphere-devrc.mk.example
  vsphere/internal/helper/computeresource/compute_resource_helper.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: bug, crash
