Repository vmware/terraform-provider-vsphere, pull requests merged in 2019-05, with the labels that each got.

#748 Document character limit on run_once_command_list
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#758 tests: Add missing ENV variable checks
  vsphere/provider_test.go
  vsphere/resource_vsphere_file_test.go
  vsphere/resource_vsphere_vapp_entity_test.go
Labels: size/S

#761 Downgrade logrus dependency
  go.mod
  go.sum
  vendor/github.com/Sirupsen/logrus/.travis.yml
  vendor/github.com/Sirupsen/logrus/CHANGELOG.md
  vendor/github.com/Sirupsen/logrus/README.md
  vendor/github.com/Sirupsen/logrus/alt_exit.go
  vendor/github.com/Sirupsen/logrus/entry.go
  vendor/github.com/Sirupsen/logrus/exported.go
  vendor/github.com/Sirupsen/logrus/go.mod
  vendor/github.com/Sirupsen/logrus/go.sum
  vendor/github.com/Sirupsen/logrus/json_formatter.go
  vendor/github.com/Sirupsen/logrus/logger.go
  vendor/github.com/Sirupsen/logrus/logrus.go
  vendor/github.com/Sirupsen/logrus/terminal_check_aix.go
  vendor/github.com/Sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/Sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/Sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/Sirupsen/logrus/text_formatter.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util.go
  vendor/golang.org/x/crypto/ssh/terminal/util_aix.go
  vendor/golang.org/x/crypto/ssh/terminal/util_bsd.go
  vendor/golang.org/x/crypto/ssh/terminal/util_linux.go
  vendor/golang.org/x/crypto/ssh/terminal/util_plan9.go
  vendor/golang.org/x/crypto/ssh/terminal/util_solaris.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/golang.org/x/sys/windows/aliases.go
  vendor/golang.org/x/sys/windows/asm_windows_386.s
  vendor/golang.org/x/sys/windows/asm_windows_amd64.s
  vendor/golang.org/x/sys/windows/asm_windows_arm.s
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/eventlog.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/golang.org/x/sys/windows/memory_windows.go
  vendor/golang.org/x/sys/windows/mkerrors.bash
  vendor/golang.org/x/sys/windows/mkerrors.go
  vendor/golang.org/x/sys/windows/mksyscall.go
  vendor/golang.org/x/sys/windows/race.go
  vendor/golang.org/x/sys/windows/race0.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/service.go
  vendor/golang.org/x/sys/windows/str.go
  vendor/golang.org/x/sys/windows/syscall.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/types_windows_386.go
  vendor/golang.org/x/sys/windows/types_windows_amd64.go
  vendor/golang.org/x/sys/windows/types_windows_arm.go
  vendor/golang.org/x/sys/windows/zerrors_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#751 only use vApp properties that are UserConfigurable
  vsphere/virtual_machine_config_structure.go
Labels: size/S
