Repository vmware/terraform-provider-vsphere, pull requests merged in 2019-11, with the labels that each got.

#876 Support for vNic resources
  vsphere/provider.go
  vsphere/resource_vsphere_vnic.go
  vsphere/resource_vsphere_vnic_test.go
  website/docs/r/vnic.html.markdown
  website/vsphere.erb
Labels: documentation, size/XXL

#840 NetworkHelper: Limit the returned scope as workaround for govmomi reflection issue
  vsphere/internal/helper/network/network_helper.go
Labels: bug, size/XS

#892 fix for compute cluster delete when Admission Policy is set to FailoverHost issue #891
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_test.go
Labels: size/S

#887 Add tfproviderlint and split acceptance tests
  .circleci/config.yml
  scripts/config_builder.sh
  scripts/esxi_restore_snapshot.sh
  scripts/test_runner.sh
  vsphere/host_network_policy_structure.go
  vsphere/internal/helper/customattribute/custom_attributes_helper.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_host_group_test.go
  vsphere/resource_vsphere_compute_cluster_test.go
  vsphere/resource_vsphere_compute_cluster_vm_affinity_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_anti_affinity_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_dependency_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_group_test.go
  vsphere/resource_vsphere_compute_cluster_vm_host_rule_test.go
  vsphere/resource_vsphere_custom_attribute_test.go
  vsphere/resource_vsphere_datastore_cluster.go
  vsphere/resource_vsphere_datastore_cluster_test.go
  vsphere/resource_vsphere_datastore_cluster_vm_anti_affinity_rule_test.go
  vsphere/resource_vsphere_distributed_port_group_test.go
  vsphere/resource_vsphere_distributed_virtual_switch_test.go
  vsphere/resource_vsphere_dpm_host_override_test.go
  vsphere/resource_vsphere_drs_vm_override_test.go
  vsphere/resource_vsphere_folder_test.go
  vsphere/resource_vsphere_ha_vm_override_test.go
  vsphere/resource_vsphere_host_port_group.go
  vsphere/resource_vsphere_host_test.go
  vsphere/resource_vsphere_host_virtual_switch_test.go
  vsphere/resource_vsphere_license.go
  vsphere/resource_vsphere_license_test.go
  vsphere/resource_vsphere_nas_datastore_test.go
  vsphere/resource_vsphere_resource_pool_test.go
  vsphere/resource_vsphere_storage_drs_vm_override_test.go
  vsphere/resource_vsphere_tag_category_test.go
  vsphere/resource_vsphere_tag_test.go
  vsphere/resource_vsphere_vapp_container_test.go
  vsphere/resource_vsphere_vapp_entity_test.go
  vsphere/resource_vsphere_virtual_disk_test.go
  vsphere/resource_vsphere_virtual_machine_migrate_test.go
  vsphere/resource_vsphere_virtual_machine_snapshot_test.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/resource_vsphere_vmfs_datastore_test.go
  vsphere/virtual_machine_config_structure.go
Labels: size/XXL

#897 Pick default datastore for extra disks
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
Labels: size/XS

#906 fix typo on no snapshots error check
  vsphere/resource_vsphere_virtual_machine_snapshot.go
Labels: bug, size/XS

#910 Return correct tag or tag category for given name
  vsphere/tags_helper.go
Labels: size/XS

#899 ha_admission_control_performance_tolerance failed to set to 0.
  vsphere/resource_vsphere_compute_cluster_test.go
Labels: enhancement, size/XS
