Repository vmware/terraform-provider-vsphere, pull requests merged in 2019-09, with the labels that each got.

#838 Update virtual_machine.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#825 Change the way we detect if a VM is in a vApp
  tf-vsphere-devrc.mk.example
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/M

#836 Add vSphere host resource
  vsphere/internal/helper/hostsystem/host_system_helper.go
  vsphere/provider.go
  vsphere/resource_vsphere_host.go
  vsphere/resource_vsphere_host_test.go
  website/docs/r/host.html.markdown
Labels: documentation, enhancement, size/XXL

#849 Changelog entries for v1.13.0
  CHANGELOG.md
Labels: size/XS
