Repository vmware/terraform-provider-vsphere, pull requests merged in 2019-10, with the labels that each got.

#853 r/host: Convert ApiDefaultTimeout to int
  vsphere/config.go
  vsphere/datacenter_helper.go
  vsphere/resource_vsphere_datacenter_test.go
  vsphere/resource_vsphere_file.go
  vsphere/resource_vsphere_file_test.go
  vsphere/resource_vsphere_host.go
  vsphere/resource_vsphere_virtual_disk.go
  vsphere/resource_vsphere_virtual_disk_test.go
Labels: size/S

#856 Add Github action for new issues
  .github/workflows/issues.yml
Labels: size/XS

#858 Update action library
  .github/workflows/issues.yml
Labels: size/XS

#860 Update GHA token
  .github/workflows/issues.yml
Labels: size/XS

#864 Put PRs into Triage backlog
  .github/workflows/issues.yml
Labels: size/XS

#862 Enable CircleCI and nightly acceptance tests
  .circleci/config.yml
  scripts/esxi_restore_snapshot.sh
  scripts/test_runner.sh
Labels: size/M

#850 [vsphere_host] Add error messages
  vsphere/resource_vsphere_host.go
Labels: enhancement, size/M

#877 r/host: Fix sidebar links
  website/docs/r/host.html.markdown
  website/vsphere.erb
Labels: documentation, size/XS

#889 Check if portgroup failure criteria is nil
  vsphere/host_network_policy_structure.go
Labels: size/XS
