Repository vmware/terraform-provider-vsphere, pull requests merged in 2019-01, with the labels that each got.

#678 r/virtual_machine: Fix virtual machine config structure schema
  vsphere/virtual_machine_config_structure.go
Labels: size/XS

#680 r/virtual_machine: Unlock memory reservation
  vsphere/virtual_machine_config_structure.go
Labels: size/S

#683 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  vsphere/config.go
  vsphere/data_source_vsphere_datacenter.go
  vsphere/data_source_vsphere_distributed_virtual_switch.go
  vsphere/data_source_vsphere_host.go
  vsphere/data_source_vsphere_vmfs_disks.go
  vsphere/datacenter_helper.go
  vsphere/datastore_structure.go
  vsphere/distributed_virtual_port_setting_structure.go
  vsphere/distributed_virtual_switch_structure.go
  vsphere/host_nas_volume_structure.go
  vsphere/host_network_policy_structure.go
  vsphere/host_port_group_structure.go
  vsphere/host_virtual_switch_structure.go
  vsphere/provider.go
  vsphere/resource_vsphere_datacenter.go
  vsphere/resource_vsphere_datacenter_test.go
  vsphere/resource_vsphere_file.go
  vsphere/resource_vsphere_file_test.go
  vsphere/resource_vsphere_host_port_group.go
  vsphere/resource_vsphere_host_virtual_switch.go
  vsphere/resource_vsphere_license.go
  vsphere/resource_vsphere_nas_datastore.go
  vsphere/resource_vsphere_virtual_disk.go
  vsphere/resource_vsphere_virtual_disk_test.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_snapshot_test.go
  vsphere/resource_vsphere_vmfs_datastore.go
Labels: size/L

#694 Fix misspelling 'opearating' to 'operating'
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS
