Repository vmware/terraform-provider-vsphere, pull requests merged in 2019-12, with the labels that each got.

#920 Unmount ISO when switching CDROM backends for a VM
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/S

#931 Migrate VM instead if destination is another host
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/S

#928 Fixed variable interpolation as per v0.12
  website/docs/index.html.markdown
Labels: documentation, size/XS

#932 Test pipeline changes
  .circleci/config.yml
  GNUmakefile
  scripts/test_runner.sh
Labels: size/S

#841 Extend ignored_guest_ips to support CIDR networks
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/resource_vsphere_virtual_machine.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, enhancement, size/S
