Repository vmware/terraform-provider-vsphere, pull requests merged in 2019-02, with the labels that each got.

#703 Fix typo
  examples/end-to-end/README.md
Labels: size/XS

#684 Add support for using guest.ipAddress for older versions of VM Tools
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/virtual_machine_guest_structure.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/M

#705 Switch to Go Modules
  .travis.yml
  GNUmakefile
  go.mod
  go.sum
Labels: size/L

#707 Update tf-vsphere-devrc.mk.example
  tf-vsphere-devrc.mk.example
Labels: size/XS

#708 Fix config for failing test
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/XS

#709 Add folder data source
  vsphere/data_source_vsphere_folder.go
  vsphere/data_source_vsphere_folder_test.go
  vsphere/provider.go
  website/docs/d/folder.html.markdown
Labels: documentation, size/M
