Repository vmware/terraform-provider-vsphere, pull requests merged in 2019-06, with the labels that each got.

#769 r/virtual_machine: Add tests for non user configurable vApp options
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/L

#787 Allow blank networkID
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
Labels: size/XS

#785 r/virtual_machine: Allow cloning of powered on VMs
  vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/L

#784 r/virtual_machine: Ignore validation when interpolation not available
  vsphere/internal/helper/structure/structure_helper.go
  vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go
  vsphere/internal/vmworkflow/virtual_machine_customize_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/XL

#792 r/virtual_machine: Add VIM session keep alive
  vsphere/config.go
  vsphere/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#793 Noticed a small typo, changed GIB to GB
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#799 Clarify virtual_machine docs
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#801 r/tag: Remove deleted tags
  vsphere/resource_vsphere_tag.go
  vsphere/resource_vsphere_tag_category.go
Labels: size/XS
