Repository vmware/terraform-provider-vsphere, pull requests merged in 2020-07, with the labels that each got.

#1135 Add go-version file
  .go-version
Labels: enhancement, size/XS, upstream

#1139 r/vm: Set guest_id before customization
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/virtual_machine_config_structure.go
Labels: size/XS

#1142 Add host_thumbprint data source
  vsphere/data_source_vsphere_host_thumbprint.go
  vsphere/data_source_vsphere_host_thumbprint_test.go
  vsphere/internal/helper/testhelper/testing.go
  vsphere/provider.go
  website/docs/d/host_thumbprint.html.markdown
  website/vsphere.erb
Labels: documentation, size/XL
