Repository vmware/terraform-provider-vsphere, pull requests merged in 2020-06, with the labels that each got.

#1092 Add release comments
  .hashibot.hcl
Labels: size/XS

#1088 Fix id in error message when category cant be load
  vsphere/resource_vsphere_custom_attribute.go
Labels: size/XS

#1094 Adding vm_storage_policy_profile resource for tag based placement policy management
  go.mod
  go.sum
  vsphere/helper_test.go
  vsphere/internal/helper/spbm/spbm_helper.go
  vsphere/internal/virtualdevice/virtual_machine_tag_rules_subresource.go
  vsphere/provider.go
  vsphere/resource_vsphere_tag_category.go
  vsphere/resource_vsphere_vm_storage_policy.go
  vsphere/resource_vsphere_vm_storage_policy_test.go
  website/docs/r/vm_storage_policy.html.markdown
  website/vsphere.erb
Labels: documentation, size/XL

#1099 Add PCI passthrough device support
  vsphere/data_source_vsphere_host_pci_device.go
  vsphere/internal/helper/computeresource/compute_resource_helper.go
  vsphere/internal/helper/envbrowse/environment_browser_helper.go
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
  vsphere/provider.go
  vsphere/resource_vsphere_virtual_machine.go
  website/docs/d/host_pci_device.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XL

#1090 Modify acceptance tests for simple test environment
  scripts/acc_setup/init.sh
  scripts/acc_setup/init/main.tf
  scripts/acc_setup/init/vcsa_deploy.json
  scripts/acc_setup/main.tf
  tf-vsphere-devrc.mk.example
  vsphere/config_test.go
  vsphere/data_source_vsphere_compute_cluster_test.go
  vsphere/data_source_vsphere_content_library_item_test.go
  vsphere/data_source_vsphere_content_library_test.go
  vsphere/data_source_vsphere_datacenter_test.go
  vsphere/data_source_vsphere_datastore_cluster_test.go
  vsphere/data_source_vsphere_datastore_test.go
  vsphere/data_source_vsphere_distributed_virtual_switch_test.go
  vsphere/data_source_vsphere_folder_test.go
  vsphere/data_source_vsphere_host_test.go
  vsphere/data_source_vsphere_network_test.go
  vsphere/data_source_vsphere_resource_pool_test.go
  vsphere/data_source_vsphere_storage_policy_test.go
  vsphere/data_source_vsphere_vapp_container_test.go
  vsphere/data_source_vsphere_virtual_machine_test.go
  vsphere/data_source_vsphere_vmfs_disks_test.go
  vsphere/helper_test.go
  vsphere/provider_test.go
  vsphere/resource_vsphere_compute_cluster_host_group_test.go
  vsphere/resource_vsphere_compute_cluster_test.go
  vsphere/resource_vsphere_compute_cluster_vm_affinity_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_anti_affinity_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_dependency_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_group_test.go
  vsphere/resource_vsphere_compute_cluster_vm_host_rule_test.go
  vsphere/resource_vsphere_content_library_item_test.go
  vsphere/resource_vsphere_content_library_test.go
  vsphere/resource_vsphere_datacenter_test.go
  vsphere/resource_vsphere_datastore_cluster_test.go
  vsphere/resource_vsphere_datastore_cluster_vm_anti_affinity_rule_test.go
  vsphere/resource_vsphere_distributed_port_group_test.go
  vsphere/resource_vsphere_distributed_virtual_switch_test.go
  vsphere/resource_vsphere_dpm_host_override_test.go
  vsphere/resource_vsphere_drs_vm_override_test.go
  vsphere/resource_vsphere_file_test.go
  vsphere/resource_vsphere_folder_migrate_test.go
  vsphere/resource_vsphere_folder_test.go
  vsphere/resource_vsphere_ha_vm_override_test.go
  vsphere/resource_vsphere_host_port_group_test.go
  vsphere/resource_vsphere_host_test.go
  vsphere/resource_vsphere_host_virtual_switch_test.go
  vsphere/resource_vsphere_license_test.go
  vsphere/resource_vsphere_nas_datastore_test.go
  vsphere/resource_vsphere_resource_pool_test.go
  vsphere/resource_vsphere_storage_drs_vm_override_test.go
  vsphere/resource_vsphere_tag_test.go
  vsphere/resource_vsphere_vapp_container_test.go
  vsphere/resource_vsphere_vapp_entity_test.go
  vsphere/resource_vsphere_virtual_disk_test.go
  vsphere/resource_vsphere_virtual_machine_migrate_test.go
  vsphere/resource_vsphere_virtual_machine_snapshot_test.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/resource_vsphere_vmfs_datastore_test.go
  vsphere/resource_vsphere_vnic_test.go
Labels: size/XXL

#1093 Add Readme improvements
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/add_labeled_issues_to_project.yml
  README.md
  _about/CODE_OF_CONDUCT.md
  _about/CONTRIBUTING.md
  _about/FAQ.md
  _about/ISSUES.md
  _about/PULL_REQUESTS.md
  _about/SUPPORT.md
Labels: documentation, size/XL

#1112 Skip PCI passthrough apply operations if there are no changes
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
Labels: size/XS

#1118 Support for SATA and IDE disks
  vsphere/data_source_vsphere_virtual_machine.go
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_migrate_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XL

#1116 Reformat examples in documentation to terraform v0.12
  website/docs/d/content_library.html.markdown
  website/docs/d/content_library_item.html.markdown
  website/docs/d/dynamic.html.markdown
  website/docs/d/host_pci_device.html.markdown
  website/docs/r/compute_cluster_host_group.html.markdown
  website/docs/r/content_library.html.markdown
  website/docs/r/content_library_item.html.markdown
  website/docs/r/custom_attribute.html.markdown
  website/docs/r/datacenter.html.markdown
  website/docs/r/distributed_virtual_switch.html.markdown
  website/docs/r/host.html.markdown
  website/docs/r/license.html.markdown
  website/docs/r/tag.html.markdown
  website/docs/r/virtual_disk.html.markdown
  website/docs/r/virtual_machine.html.markdown
  website/docs/r/vnic.html.markdown
Labels: documentation, size/L
