Repository vmware/terraform-provider-vsphere, pull requests merged in 2020-03, with the labels that each got.

#983 [circleci] reorder tests
  .circleci/config.yml
Labels: size/XS

#986 Pre release cleanup
  vsphere/host_port_group_structure.go
  vsphere/resource_vsphere_host_port_group.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/XS

#989 Update broken link to VMWare guest ID docs
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#990 Add configurable timeout for VM PowerOn operations
  vsphere/internal/helper/viapi/vim_helper.go
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: bug, size/M

#985 Content Library
  vendor/github.com/vmware/govmomi/vapi/library/library.go
  vendor/github.com/vmware/govmomi/vapi/library/library_file.go
  vendor/github.com/vmware/govmomi/vapi/library/library_item.go
  vendor/github.com/vmware/govmomi/vapi/library/library_item_downloadsession_file.go
  vendor/github.com/vmware/govmomi/vapi/library/library_item_updatesession.go
  vendor/github.com/vmware/govmomi/vapi/library/library_item_updatesession_file.go
  vendor/github.com/vmware/govmomi/vapi/vcenter/vcenter_ovf.go
  vendor/github.com/vmware/govmomi/vapi/vcenter/vcenter_vmtx.go
  vendor/modules.txt
  vsphere/data_source_vsphere_content_library.go
  vsphere/data_source_vsphere_content_library_item.go
  vsphere/data_source_vsphere_content_library_item_test.go
  vsphere/data_source_vsphere_content_library_test.go
  vsphere/helper_test.go
  vsphere/internal/helper/contentlibrary/content_library_helper.go
  vsphere/internal/helper/viapi/vim_helper.go
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
  vsphere/provider.go
  vsphere/resource_vsphere_content_library.go
  vsphere/resource_vsphere_content_library_item.go
  vsphere/resource_vsphere_content_library_item_test.go
  vsphere/resource_vsphere_content_library_test.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/d/content_library.html.markdown
  website/docs/d/content_library_item.html.markdown
  website/docs/r/content_library.html.markdown
  website/docs/r/content_library_item.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: dependencies, documentation, size/XXL

#1006 Add poweron_timeout default during import
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/XS

#1008 Add CheckDestroy to Content Library resources
  vsphere/resource_vsphere_content_library_item_test.go
  vsphere/resource_vsphere_content_library_test.go
Labels: size/S

#1005 Fix working with orphaned devices
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
Labels: size/XS

#1013 Create labeled_issues.yml
  .github/workflows/labeled_issues.yml
Labels: size/XS

#1014 r/virtual_machine: Ignore guest_id with content library
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/XS

#1001 handling cases of network port groups with same name
  vsphere/data_source_vsphere_network.go
  vsphere/data_source_vsphere_network_test.go
  vsphere/internal/helper/network/network_helper.go
Labels: enhancement, size/L
