Repository vmware/terraform-provider-vsphere, pull requests merged in 2020-08, with the labels that each got.

#1151 r/compute_cluster: Add vSAN support
  vsphere/internal/helper/clustercomputeresource/cluster_compute_resource_helper.go
  vsphere/internal/helper/structure/structure_helper.go
  vsphere/internal/helper/vsansystem/vsansystem_helper.go
  vsphere/resource_vsphere_compute_cluster.go
  website/docs/r/compute_cluster.html.markdown
Labels: documentation, size/XL

#1144 Add roles and permission resources
  vsphere/data_source_vsphere_role.go
  vsphere/data_source_vsphere_role_test.go
  vsphere/helper_test.go
  vsphere/internal/administrationroles/vsphere_permission_subresource.go
  vsphere/internal/helper/utils/entityIdToManagedObjectId.go
  vsphere/provider.go
  vsphere/resource_vsphere_entity_permissions.go
  vsphere/resource_vsphere_entity_permissions_test.go
  vsphere/resource_vsphere_role.go
  vsphere/resource_vsphere_role_test.go
  website/docs/d/vsphere_role.html.markdown
  website/docs/r/vsphere_entity_permissions.html.markdown
  website/docs/r/vsphere_role.html.markdown
  website/vsphere.erb
Labels: documentation, size/XL

#1120 Add import for vsphere_virtual_disk
  vsphere/internal/helper/virtualdisk/virtual_disk_helper.go
  vsphere/resource_vsphere_virtual_disk.go
  vsphere/resource_vsphere_virtual_disk_test.go
  website/docs/r/virtual_disk.html.markdown
Labels: documentation, size/M

#1157 Merged the virtual machine configuration schema between the both the resource and datasource
  vsphere/data_source_vsphere_virtual_machine.go
  vsphere/data_source_vsphere_virtual_machine_test.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/virtual_machine_config_structure.go
  website/docs/d/virtual_machine.html.markdown
Labels: documentation, size/L

#1158 Allow performing a linked-clone from a template without requiring snapshots
  vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/S

#1162 Fix vnic import
  vsphere/resource_vsphere_vnic.go
Labels: size/S

#1161 Ignore thin_provisioned and eagerly_scrub during DiskPostCloneOperation
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
Labels: size/XS

#1175 Add hall of fame to README.md
  README.md
Labels: size/XS

#1179 Skip SCSI controller check when empty
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
Labels: size/XS

#1193 Fix non inclusive language
  vsphere/resource_vsphere_folder_migrate.go
  vsphere/resource_vsphere_virtual_machine_migrate.go
Labels: size/XS

#1188 Set SCSI controller type to unknown when nil
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
Labels: bug, size/XS

#1187 Keep progress channel open
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
Labels: bug, size/XS

#1186 Ignore nil objects in host network
  vsphere/host_network_policy_structure.go
Labels: bug, size/XS

#1185 Make storage_policy_id computed.
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/virtual_machine_config_structure.go
Labels: bug, size/XS
