Repository vmware/terraform-provider-vsphere, pull requests merged in 2020-02, with the labels that each got.

#963 Properly set up environment for REST session persistence
  vsphere/config.go
Labels: size/M

#970 Base storage_policy_id off vm
  vsphere/internal/helper/provider/provider_helper.go
  vsphere/internal/helper/spbm/spbm_helper.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
Labels: size/XS

#959 Optimize OS family query
  vsphere/internal/helper/envbrowse/environment_browser_helper.go
Labels: enhancement, size/XS
