Repository vmware/terraform-provider-vsphere, pull requests merged in 2020-04, with the labels that each got.

#1015 Adding virtual_switch_uuid arguments in the documentation for vsphere_network datasource
  website/docs/d/network.html.markdown
Labels: documentation, size/XS

#1018 Add task to move issues that require investigation
  .github/workflows/labeled_issues.yml
Labels: size/XS

#1019 Fix test name for linter
  vsphere/data_source_vsphere_network_test.go
Labels: size/XS

#1022 Delete old issue template file
  .github/ISSUE_TEMPLATE.md
  .github/pull_request_template.md
Labels: size/M

#1025 Add job to move crashes to current work list
  .github/workflows/labeled_issues.yml
Labels: size/XS

#1026 r/vm: Only upgrade hardware version when target set
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/XS

#1029 Add 2nd disk to each controller
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/XS

#987 Update resource vsphere file to support vmdk files
  vsphere/resource_vsphere_file.go
Labels: enhancement, size/M

#1032 Fix disk controller sorting
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
Labels: size/XS

#1031 SCSI controller tests
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/XS

#1038 Add issue triage actions
  .github/workflows/add_labeled_issues_to_project.yml
  .github/workflows/add_new_issues_to_project.yml
  .hashibot.hcl
  prune_stale_issues.yml
Labels: size/XS

#1050 Move pruning action to appropriate folder
  .github/workflows/prune_stale_issues.yml
Labels: size/XS

#1051 Use govmomi cache.Session for REST sessions
  go.mod
  go.sum
  vendor/github.com/vmware/govmomi/CHANGELOG.md
  vendor/github.com/vmware/govmomi/CONTRIBUTING.md
  vendor/github.com/vmware/govmomi/Makefile
  vendor/github.com/vmware/govmomi/object/common.go
  vendor/github.com/vmware/govmomi/object/network.go
  vendor/github.com/vmware/govmomi/object/opaque_network.go
  vendor/github.com/vmware/govmomi/object/task.go
  vendor/github.com/vmware/govmomi/pbm/client.go
  vendor/github.com/vmware/govmomi/property/collector.go
  vendor/github.com/vmware/govmomi/property/filter.go
  vendor/github.com/vmware/govmomi/property/wait.go
  vendor/github.com/vmware/govmomi/session/cache/session.go
  vendor/github.com/vmware/govmomi/session/manager.go
  vendor/github.com/vmware/govmomi/vapi/internal/internal.go
  vendor/github.com/vmware/govmomi/vapi/library/library.go
  vendor/github.com/vmware/govmomi/vapi/library/library_item.go
  vendor/github.com/vmware/govmomi/vapi/library/library_item_updatesession_file.go
  vendor/github.com/vmware/govmomi/vapi/rest/client.go
  vendor/github.com/vmware/govmomi/vapi/vcenter/vcenter_ovf.go
  vendor/github.com/vmware/govmomi/vapi/vcenter/vcenter_vmtx.go
  vendor/github.com/vmware/govmomi/vim25/client.go
  vendor/github.com/vmware/govmomi/vim25/soap/client.go
  vendor/github.com/vmware/govmomi/vim25/types/types.go
  vendor/github.com/vmware/govmomi/vim25/xml/LICENSE
  vendor/github.com/vmware/govmomi/vim25/xml/marshal.go
  vendor/github.com/vmware/govmomi/vim25/xml/read.go
  vendor/github.com/vmware/govmomi/vim25/xml/typeinfo.go
  vendor/github.com/vmware/govmomi/vim25/xml/xml.go
  vendor/modules.txt
  vsphere/config.go
Labels: dependencies, size/XXL

#1039 Only compare bus number if different
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
Labels: size/XS

#1054 Use Go 1.13.x for Travis
  .travis.yml
Labels: size/XS

#1046 Replace sysprep.inf with sysprep.xml in docs
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#1045 Mark product_key as sensitive
  vsphere/internal/vmworkflow/virtual_machine_customize_subresource.go
Labels: size/XS

#1056 Increase max hw version for vSphere 7.0
  vsphere/virtual_machine_config_structure.go
Labels: size/XS

#1055 Only include hardware version in CreateSpecs
  vsphere/virtual_machine_config_structure.go
Labels: size/XS
