Repository vmware/terraform-provider-vsphere, pull requests merged in 2020-01, with the labels that each got.

#938 fix typos and incorrect ref to id and not moid (managed) in the vsphere_vapp_entity docs
  website/docs/r/vapp_entity.html.markdown
Labels: documentation, size/XS

#941 Fix handling of child vApp containers
  vsphere/resource_vsphere_vapp_container.go
  vsphere/resource_vsphere_vapp_container_test.go
Labels: size/M

#944 Do not throw error when disk path is not known yet
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: bug, size/M

#950 Housekeeping
  .circleci/config.yml
  go.mod
  go.sum
Labels: size/M

#902 Set guest IP addresses on data.vsphere_virtual_machine if available
  vsphere/data_source_vsphere_virtual_machine.go
Labels: enhancement, size/XS

#942 b/virtual_disk: enforce vmdk suffix
  vsphere/resource_vsphere_virtual_disk.go
Labels: size/XS

#933 Do not set the datastoreID in RelocateSpec when datastore_cluster is set
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/XS

#953 [vapp] Remove hardcoded values from test code
  vsphere/resource_vsphere_vapp_container_test.go
Labels: size/XS

#956 Fix failing compute cluster test
  go.sum
  vsphere/resource_vsphere_compute_cluster_test.go
Labels: size/XS
