Repository vmware/terraform-provider-vsphere, pull requests merged in 2020-05, with the labels that each got.

#1060 Update column to which crashes are moved
  .github/workflows/add_labeled_issues_to_project.yml
Labels: size/XS

#1052 Deploy OVF from remote Url and local system
  vendor/github.com/vmware/govmomi/ovf/cim.go
  vendor/github.com/vmware/govmomi/ovf/doc.go
  vendor/github.com/vmware/govmomi/ovf/env.go
  vendor/github.com/vmware/govmomi/ovf/env_test.go
  vendor/github.com/vmware/govmomi/ovf/envelope.go
  vendor/github.com/vmware/govmomi/ovf/manager.go
  vendor/github.com/vmware/govmomi/ovf/ovf.go
  vendor/github.com/vmware/govmomi/ovf/ovf_test.go
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
  vsphere/internal/vmworkflow/virtual_machine_ovfdeploy_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/virtual_machine_config_structure.go
  website/docs/r/virtual_machine.html.markdown
Labels: dependencies, documentation, enhancement, size/XXL

#1062 Add release badge and license badge
  README.md
Labels: size/XS

#1063 fixing OVF deploy documentation bugs
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#1067 r/vm: Skip unexpected NIC entries
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
Labels: size/XS

#1077 Respect `session_persistence` for rest sessions
  vsphere/config.go
Labels: size/XS

#1085 Specify cluster membership management
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_host.go
  website/docs/r/compute_cluster.html.markdown
  website/docs/r/host.html.markdown
Labels: documentation, size/S

#1084 Move ovf argument validation out of CustomizeDiff
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/XS

#1083 Disconnect on delete instead of maintenance mode
  vsphere/resource_vsphere_host.go
Labels: size/XS

#1082 Adding vapp properties while OVF deployment
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/virtual_machine_config_structure.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/S
