Repository vmware/terraform-provider-vsphere, pull requests merged in 2020-09, with the labels that each got.

#1197 r/content_library: Subscription and publication support
  vsphere/internal/helper/contentlibrary/content_library_helper.go
  vsphere/resource_vsphere_content_library.go
  vsphere/resource_vsphere_content_library_test.go
  website/docs/r/content_library.html.markdown
Labels: documentation, size/XL

#1196 r/content__library_item: Local upload, OVA, and vm-template sources
  vsphere/internal/helper/contentlibrary/content_library_helper.go
  vsphere/resource_vsphere_content_library_item.go
  vsphere/resource_vsphere_content_library_item_migrate.go
  vsphere/resource_vsphere_content_library_item_test.go
  website/docs/r/content_library_item.html.markdown
Labels: documentation, size/XL

#1198 r/vm: Content library vm-template, disk type, and vApp props
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/L

#1184 Add type to content library item data source
  vsphere/data_source_vsphere_content_library_item.go
  website/docs/d/content_library_item.html.markdown
  website/vsphere.erb
Labels: documentation, enhancement, size/XS

#1208 Import ditributed port group using moid
  vsphere/resource_vsphere_distributed_port_group.go
  website/docs/r/distributed_port_group.html.markdown
Labels: documentation, size/XS

#1203 r/datastore_cluster: Fix missing field in import
  vsphere/internal/helper/datacenter/datacenter_helper.go
  vsphere/resource_vsphere_datastore_cluster.go
Labels: size/XS

#1194 r/host_port_group: Add support for importing
  vsphere/host_port_group_structure.go
  vsphere/resource_vsphere_host_port_group.go
  website/docs/r/host_port_group.html.markdown
  website/docs/r/vnic.html.markdown
Labels: documentation, size/S

#1146 Networking additions [WIP]
  vsphere/distributed_virtual_port_setting_structure.go
  vsphere/distributed_virtual_switch_structure.go
  website/docs/r/distributed_virtual_switch.html.markdown
Labels: documentation, size/L

#1207 Convert folder path to MOID
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/XS
