Repository vmware/terraform-provider-vsphere, pull requests merged in 2021-03, with the labels that each got.

#1311 Sorting permissions object on username/group name before storing.
  vsphere/resource_vsphere_entity_permissions.go
  website/docs/r/vsphere_entity_permissions.html.markdown
Labels: documentation, size/S

#1339 OVF deployment options support
  vsphere/data_source_vsphere_ovf_vm_template.go
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/internal/vmworkflow/virtual_machine_ovfdeploy_subresource.go
  vsphere/provider.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/d/ovf_vm_template.html.markdown
  website/docs/r/virtual_machine.html.markdown
  website/vsphere.erb
Labels: documentation, size/XL

#1363 Support vsphere 7 for dvs
  vsphere/distributed_virtual_switch_helper.go
Labels: size/XS

#1365 Bump Go to 1.16
  .circleci/config.yml
  .go-version
  .travis.yml
  GNUmakefile
  README.md
  _about/CONTRIBUTING.md
  go.mod
  scripts/config_builder.sh
  vendor/modules.txt
Labels: dependencies, size/S

#1367 rollback to 1.16.0
  .go-version
Labels: size/XS
