Repository vmware/terraform-provider-vsphere, pull requests merged in 2021-06, with the labels that each got.

#1418 Migrate most GitHub HashiBot behaviors to GitHub Actions
  .github/labeler-issue-triage.yml
  .github/labeler-pull-request-triage.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issue-opened.yml
  .github/workflows/lock.yml
  .github/workflows/pull-request.yml
  .hashibot.hcl
Labels: size/M

#1360 #1190 - Add replacement trigger to virtual machine resource
  .gitignore
  CHANGELOG.md
  vsphere/virtual_machine_config_structure.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#1419 v2.0.0 release
  CHANGELOG.md
  README.md
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XL

#1423 Only set vvtd/vbs if vsphere version is newer than 6.5
  vsphere/virtual_machine_config_structure.go
Labels: size/XS

#1420 Migrate GitHub HashiBot release_commenter and pull_request_size_labeler behavior to GitHub Actions
  .github/workflows/milestone-closed.yml
  .github/workflows/pull-request.yml
  .hashibot.hcl
Labels: size/M

#1433 Fix cdrom import issues
  vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/M

#1430 do not access vvtd and vbs fields unless on we are running on vsphere > 6.5
  vsphere/data_source_vsphere_virtual_machine.go
  vsphere/internal/helper/viapi/vim_helper.go
  vsphere/internal/helper/viapi/vim_helper_test.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/virtual_machine_config_structure.go
Labels: size/M

#1431 Add new option for syncing time on vSphere 7 U1 and above
  vsphere/virtual_machine_config_structure.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/S

#1434 Changelog update before v2.0.2
  CHANGELOG.md
Labels: size/XS

#1432 `vsan_disk_group` should be of type `TypeSet`
  vsphere/resource_vsphere_compute_cluster.go
Labels: size/XS
