Repository vmware/terraform-provider-vsphere, pull requests merged in 2021-04, with the labels that each got.

#1381 Acceptance test simplification and related changes
  .gitignore
  scripts/packet/devrc.tpl
  scripts/packet/main.tf.phase1
  scripts/packet/main.tf.phase2
  scripts/packet/main.tf.phase3
  scripts/packet/vcsa_deploy.json
  vsphere/data_source_vsphere_distributed_virtual_switch_test.go
  vsphere/data_source_vsphere_host_test.go
  vsphere/distributed_virtual_switch_structure.go
  vsphere/helper_test.go
  vsphere/host_nas_volume_structure.go
  vsphere/internal/helper/clustercomputeresource/cluster_compute_resource_helper.go
  vsphere/internal/helper/testhelper/testing.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_host_group_test.go
  vsphere/resource_vsphere_compute_cluster_test.go
  vsphere/resource_vsphere_compute_cluster_vm_affinity_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_anti_affinity_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_dependency_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_group_test.go
  vsphere/resource_vsphere_compute_cluster_vm_host_rule_test.go
  vsphere/resource_vsphere_datacenter_test.go
  vsphere/resource_vsphere_datastore_cluster_vm_anti_affinity_rule_test.go
  vsphere/resource_vsphere_distributed_port_group.go
  vsphere/resource_vsphere_distributed_port_group_test.go
  vsphere/resource_vsphere_distributed_virtual_switch_test.go
  vsphere/resource_vsphere_dpm_host_override_test.go
  vsphere/resource_vsphere_drs_vm_override_test.go
  vsphere/resource_vsphere_entity_permissions_test.go
  vsphere/resource_vsphere_file_test.go
  vsphere/resource_vsphere_ha_vm_override_test.go
  vsphere/resource_vsphere_host_port_group_test.go
  vsphere/resource_vsphere_host_test.go
  vsphere/resource_vsphere_host_virtual_switch_test.go
  vsphere/resource_vsphere_license_test.go
  vsphere/resource_vsphere_nas_datastore.go
  vsphere/resource_vsphere_nas_datastore_test.go
  vsphere/resource_vsphere_resource_pool_test.go
  vsphere/resource_vsphere_storage_drs_vm_override_test.go
  vsphere/resource_vsphere_vapp_container_test.go
  vsphere/resource_vsphere_vapp_entity_test.go
  vsphere/resource_vsphere_virtual_disk_test.go
  vsphere/resource_vsphere_virtual_machine_migrate_test.go
  vsphere/resource_vsphere_virtual_machine_snapshot_test.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/resource_vsphere_vmfs_datastore_test.go
  vsphere/resource_vsphere_vnic.go
  vsphere/resource_vsphere_vnic_test.go
Labels: size/XXL

#1391 Update max hardware version
  vsphere/virtual_machine_config_structure.go
Labels: size/XS

#1392 Change the way we set the timeout for maintenance mode
  CHANGELOG.md
  vsphere/internal/helper/clustercomputeresource/cluster_compute_resource_helper.go
  vsphere/internal/helper/hostsystem/host_system_helper.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_host.go
Labels: size/S

#1398 Fix crash when creating an OVF import
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
Labels: size/XS

#1376 Change vnic netstack property default value to 'defaultTcpipStack' as the 'default' value does not exist
  vsphere/resource_vsphere_vnic.go
Labels: size/XS

#1397 Fix calculation of diskCapacityInGiB by rounding up
  vsphere/internal/helper/structure/structure_helper.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource_test.go
Labels: size/S
