Repository vmware/terraform-provider-vsphere, pull requests merged in 2021-12, with the labels that each got.

#1519 Update settings for GitHub Actions
  .github/labeler-pull-request-triage.yml
  .github/workflows/issue-comment-created.yml
  .github/workflows/issue-opened.yml
  .github/workflows/lock.yml
Labels: size/S

#1408 Address PolicyIDByVirtualMachine and PolicyIDByVirtualDisk errors when deploying VM on ESXi.
  vsphere/internal/helper/spbm/spbm_helper.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/S, next-release-candidate

#1531 Update FAQ.md with current team + adds
  _about/FAQ.md
Labels: documentation, size/XS

#1532 Fix silent failure on vm datasource
  vsphere/data_source_vsphere_virtual_machine.go
  website/docs/d/virtual_machine.html.markdown
Labels: documentation, size/XS, provider

#1486 force reconfigure due to race condition
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/XS

#1539 Update GHA for issues/pull-request locking
  .github/workflows/lock.yml
Labels: size/XS, provider
