Repository vmware/terraform-provider-vsphere, pull requests merged in 2021-11, with the labels that each got.

#1497 Update bug-report.md to include vSphere version
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: size/XS

#1489 EFI firmware should be lowercase
  vsphere/data_source_vsphere_ovf_vm_template.go
  vsphere/virtual_machine_config_structure.go
  website/docs/d/virtual_machine.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#1451 Update content_library.html.markdown
  website/docs/r/content_library.html.markdown
Labels: documentation, size/XS

#1526 Update configs to default to vSphere 7 on equinix
  scripts/packet/devrc.tpl
  scripts/packet/main.tf.phase1
  scripts/packet/main.tf.phase2
  scripts/packet/main.tf.phase3
Labels: size/M
