Repository vmware/terraform-provider-vsphere, pull requests merged in 2021-05, with the labels that each got.

#1301 Manual start of REST keepalive w/ cached session
  vsphere/config.go
Labels: size/XS

#1287 Enabling VBS (vbsEnabled) and I/O MMU (vvtdEnabled)
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/virtual_machine_config_structure.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/M

#1402 replace travis with gh actions
  .github/workflows/unit_tests.yaml
  .travis.yml
Labels: size/S

#1361 Fix compare for VM Config spec change
  vsphere/virtual_machine_config_structure.go
Labels: size/XS

#1199 Allow vApp userConfigurable=false properties to be configured
  vsphere/internal/vmworkflow/virtual_machine_ovfdeploy_subresource.go
  vsphere/virtual_machine_config_structure.go
Labels: size/S

#1403 address codeql warnings
  vsphere/data_source_vsphere_host_pci_device.go
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
  vsphere/resource_vsphere_compute_cluster_vm_affinity_rule.go
  vsphere/resource_vsphere_compute_cluster_vm_anti_affinity_rule.go
  vsphere/resource_vsphere_compute_cluster_vm_dependency_rule.go
  vsphere/resource_vsphere_compute_cluster_vm_host_rule.go
  vsphere/resource_vsphere_datastore_cluster_vm_anti_affinity_rule.go
  vsphere/resource_vsphere_virtual_machine_migrate.go
Labels: size/S

#1274 Added network_interfaces property to virtual machine data source
  vsphere/data_source_vsphere_virtual_machine.go
  vsphere/data_source_vsphere_virtual_machine_test.go
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  website/docs/d/virtual_machine.html.markdown
Labels: documentation, size/L
