Repository vmware/terraform-provider-vsphere, pull requests merged in 2022-03, with the labels that each got.

#1609 Move to GH action based release
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yml
  terraform-registry-manifest.json
Labels: size/M, provider, needs-review, github/actions

#1610 Update `master` references to `main`
  .circleci/config.yml
  .github/issue_greeting_template.md
  .github/pull_request_template.md
  .github/workflows/codeql-analysis.yml
  CHANGELOG.md
  scripts/config_builder.sh
Labels: documentation, size/XS, provider, inclusive-language, needs-review, github/repo

#1407 Add check for `vsphere_virtual_machine` power state
  vsphere/resource_vsphere_virtual_machine.go
  website/docs/r/virtual_machine.html.markdown
Labels: enhancement, documentation, size/XS, provider, under-review, area/vm

#1619 feat: Add support for custom attributes on `r/vsphere_host`
  vsphere/resource_vsphere_host.go
  website/docs/r/host.html.markdown
Labels: enhancement, documentation, size/L, provider, needs-review

#1620 docs: Update `r/vsphere_resource_pool` docs
  website/docs/r/resource_pool.html.markdown
Labels: documentation, size/M, needs-review, area/clustering

#1629 fix: Update `DiskCloneValidateOperation` and `DiskImportOperation`
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
Labels: bug, size/XS, provider, needs-review, area/vm, area/storage

#1633 fix: Prevent unsupported traffic classes to be set and cause crash
  vsphere/distributed_virtual_switch_structure.go
  vsphere/util.go
  website/docs/r/distributed_virtual_switch.html.markdown
Labels: documentation, size/XS, provider, needs-review

#1627 fix: Only consider `VirtualPCIPassthroughDeviceBackingInfo` devices
  vsphere/resource_vsphere_virtual_machine.go
Labels: bug, crash, size/XS, provider, needs-review

#1637 Fix tests to pass even without DHCP
  scripts/packet/devrc.tpl
  scripts/packet/main.tf.phase3
  vsphere/resource_vsphere_distributed_port_group_test.go
  vsphere/resource_vsphere_storage_drs_vm_override_test.go
  vsphere/resource_vsphere_tag_test.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/L, provider

#1640 chore: Add necessary bits to onboard project to the Releases API
  .github/workflows/release.yml
  .goreleaser.yml
  .release/release-metadata.hcl
Labels: size/M, provider, chore

#1641 Revert "chore: Add necessary bits to onboard project to the Releases API"
  .github/workflows/release.yml
  .goreleaser.yml
  .release/release-metadata.hcl
Labels: size/M, provider

#1643 Generate VMFS disk IDs for tests
  scripts/packet/devrc.tpl
  scripts/packet/main.tf.phase2
  scripts/packet/main.tf.phase3
  scripts/packet/versions.tf
Labels: size/XS
