Repository vmware/terraform-provider-vsphere, pull requests merged in 2022-06, with the labels that each got.

#1660 fix(docs): correct typo
  website/docs/index.html.markdown
Labels: community/contribution, documentation, size/XS, provider

#1674 fix:GHA failures on `add_labeled_issues_to_project.yml`
  .github/workflows/add_labeled_issues_to_project.yml
Labels: size/XS, provider, needs-review, github/actions

#1672 docs: update docs index
  website/docs/index.html.markdown
Labels: documentation, size/L, provider, needs-review, area/vm, area/storage

#1671 docs: update `r/host_port_group` docs
  website/docs/r/host_port_group.html.markdown
Labels: documentation, size/M, needs-review, area/networking

#1665 fix: Local iso upload in content library item
  vsphere/internal/helper/contentlibrary/content_library_helper.go
Labels: bug, community/contribution, size/XS, provider, needs-review, area/content-library

#1679 Update Line 195 from privledge to privilege
  website/docs/index.html.markdown
Labels: documentation, size/XS, provider
