Repository vmware/terraform-provider-vsphere, pull requests merged in 2022-08, with the labels that each got.

#1704 docs: Update README.md
  README.md
Labels: documentation, size/XS, provider

#1711 docs: Update README.md with context for "VMware vSphere"
  README.md
Labels: documentation, size/XS, provider

#1712 Update `README.md` with context for "VMware vSphere"
  README.md
Labels: documentation, size/XS, provider

#1713 chore: update greeting template
  .github/issue_greeting_template.md
Labels: size/XS, provider, github/actions

#1707 chore: enable dependabot
  .github/dependabot.yml
Labels: size/XS, provider/technical-debt, provider, chore, github/actions

#1721 fix: update CodeQL action to removes the deprecated step
  .github/workflows/codeql-analysis.yml
Labels: bug, size/M, provider, github/actions

#1598 feat: Add support for paravirtual RDMA network interface adapter type
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  website/docs/d/virtual_machine.html.markdown
Labels: enhancement, documentation, size/XS, provider, needs-review, area/vm, area/networking

#1729 chore: remove legacy docs `.erb` config
  website/vsphere.erb
Labels: documentation, size/L, chore

#1726 feat: Add support for vSAN performance service configuration
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_test.go
  website/docs/r/compute_cluster.html.markdown
Labels: documentation, size/l, provider
