Repository vmware/terraform-provider-vsphere, pull requests merged in 2022-07, with the labels that each got.

#1675 docs: update `r/vsphere_host` docs
  website/docs/r/host.html.markdown
Labels: documentation, size/XS, needs-review, area/host

#1681 docs: update docs index
  website/docs/d/compute_cluster_host_group.html.markdown
  website/docs/d/ovf_vm_template.html.markdown
  website/docs/index.html.markdown
Labels: documentation, size/XS, provider, needs-review

#1687 fix: Update `docscheck.sh` to check data source docs
  scripts/docscheck.sh
Labels: enhancement, documentation, size/XS, needs-review

#1696 repo: Update bug report template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: size/XS, provider, github/repo

#1697 repo: Remove legacy testing example
  test-infra/main.tf
Labels: size/M, provider, github/repo

#1695 enhance: Allow `standby_nics` as optional attribute
  vsphere/resource_vsphere_host_virtual_switch.go
  vsphere/resource_vsphere_host_virtual_switch_test.go
  website/docs/r/host_virtual_switch.html.markdown
Labels: enhancement, documentation, size/XS, provider, area/networking

#1645 feat: Set timeout for `v/virtual_machine` reconfigure task
  vsphere/helper_test.go
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: community/contribution, size/XS, provider, planned, needs-review, area/vm

#1631 feat: Add support up to 2 CD-ROMs on `r/virtual_machine`
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: enhancement, documentation, size/M, provider, planned, area/vm

#1700 Update vsphere_compute_cluster_vm_anti_affinity_rule docs
  website/docs/r/compute_cluster_vm_anti_affinity_rule.html.markdown
Labels: documentation, size/XS

#1701 chore: Update `vmware/govmomi` v0.29.0
  go.mod
  go.sum
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/XS, provider
