Repository vmware/terraform-provider-vsphere, pull requests merged in 2022-09, with the labels that each got.

#1749 fix: `sdrs_advanced_options` on `r/datastore_cluster`
  vsphere/resource_vsphere_datastore_cluster.go
Labels: bug, size/xs, provider, needs-review, area/storage

#1745 feat: add support for vSAN unmap
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_test.go
  website/docs/r/compute_cluster.html.markdown
Labels: documentation, size/l, provider, area/storage, area/clustering

#1743 fix: address `misspell` linter errors observed in `golangci-lint`
  vsphere/data_source_vsphere_dynamic.go
  vsphere/internal/helper/virtualdisk/virtual_disk_helper.go
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
Labels: size/xs, provider/technical-debt, provider

#1747 fix: address `gostaticanalysis/nilerr` error in `content_library_helper.go`
  vsphere/internal/helper/contentlibrary/content_library_helper.go
Labels: size/xs, provider/technical-debt, provider

#1741 fix: address `io/ioutil` depreciation
  vsphere/config_test.go
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
  vsphere/resource_vsphere_file_test.go
Labels: size/xs, provider/technical-debt, provider

#1742 fix: address `gofmt` errors observed in `golangci-lint`
  vsphere/config.go
  vsphere/data_source_vsphere_datacenter.go
  vsphere/helper_test.go
  vsphere/internal/helper/customattribute/custom_attributes_helper.go
  vsphere/internal/helper/structure/structure_helper.go
  vsphere/tags_helper.go
Labels: size/s, provider/technical-debt, provider

#1755 docs: update `INSTALL.md`
  docs/INSTALL.md
Labels: documentation, size/s, provider
