Repository vmware/terraform-provider-vsphere, pull requests merged in 2022-02, with the labels that each got.

#1568 Update `resource/distributed_virtual_switch` and `vsphere_distributed_port_group` resource docs.
  website/docs/r/distributed_port_group.html.markdown
  website/docs/r/distributed_virtual_switch.html.markdown
Labels: documentation, size/XL

#1569 Update `vsphere_virtual_disk` docs and id error msg
  vsphere/resource_vsphere_virtual_disk.go
  website/docs/r/virtual_disk.html.markdown
Labels: bug, documentation, size/S, provider

#1566 Update docs example for templates that use ISO transport
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS

#1570 Add GitHub Action for state issues and pull requests
  .github/workflows/stale.yml
Labels: enhancement, size/S, provider, needs-review

#1336 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation, size/XS, provider, needs-review

#1546 Fix disk migration when `datastore_cluster_id` changes
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
Labels: bug, size/XS, provider

#1575 Add GitHub Action for issue greeting
  .github/issue_greeting_template.md
  .github/workflows/issue_greeting.yml
  docs/ISSUES.md
Labels: documentation, size/S, provider, chore, needs-review

#1576 Update `vsphere_virtual_machine` resource doc for memory hot add >3GB
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS, needs-review

#1577 Update `resource/content_library` docs
  website/docs/r/content_library.html.markdown
Labels: documentation, size/M, needs-review

#1522 Update `vsphere_virtual_machine` resource docs with reboot conditions
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/S, needs-review

#1409 Fix VMDK upload failure on ESXi host using `vspshere_file` resource.
  vsphere/resource_vsphere_file.go
Labels: bug, size/S, provider, needs-review

#1579 Check for 404 Not found on tag and tag_category
  vsphere/resource_vsphere_tag.go
  vsphere/resource_vsphere_tag_category.go
Labels: bug, size/XS, provider, needs-review

#1468 Set `devices` parameter as optional for `vsphere_distributed_switch` resource
  vsphere/distributed_virtual_switch_structure.go
  website/docs/r/distributed_virtual_switch.html.markdown
Labels: enhancement, documentation, size/XS, provider, needs-review

#1581 Add Ryan Johnson as collaborator
  docs/FAQ.md
Labels: documentation, size/XS, provider

#1583 Migrate issue templates to forms
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: enhancement, size/XL, provider, needs-review

#1588 Set `annotation` on `r/vsphere_virtual_machine` to computed
  vsphere/virtual_machine_config_structure.go
Labels: bug, size/XS, provider, needs-review

#1586 Update `resource/content_library_item` docs
  website/docs/r/content_library_item.html.markdown
Labels: documentation, size/M, needs-review

#1590 Update `r/vsphere_file` resource and docs
  vsphere/resource_vsphere_file.go
  website/docs/r/file.html.markdown
Labels: bug, documentation, size/M, provider, needs-review, area/storage

#1595 Update `r/vsphere_virtual_machine` docs
  website/docs/r/virtual_machine.html.markdown
Labels: bug, documentation, size/S, area/vm

#1506 Add `tools_upgrade_policy` argument to the `vsphere_virtual_machine` resource
  vsphere/virtual_machine_config_structure.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/XS, provider, needs-review, area/vm

#1606 Bump Go to v1.16.14
  .go-version
Labels: size/XS, provider, chore, needs-review
