Repository vmware/terraform-provider-vsphere, pull requests merged in 2023-11, with the labels that each got.

#2052 chore(deps): bump google.golang.org/grpc from 1.57.0 to 1.57.1
  go.mod
  go.sum
Labels: size/xs, chore

#1885 feat: add vsan stretched cluster support
  CHANGELOG.md
  vsphere/internal/helper/vsanclient/vsan_client_helper.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_test.go
  website/docs/r/compute_cluster.html.markdown
Labels: enhancement, documentation, size/xl, provider, area/storage, area/clustering

#1969 feat: add vsan fault domain support
  CHANGELOG.md
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_test.go
  website/docs/r/compute_cluster.html.markdown
Labels: enhancement, documentation, size/l, provider, area/storage, area/clustering

#2059 feat: add support for sr-iov network interface
  CHANGELOG.md
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource_test.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/xl, provider

#2064 fix: separate vsan fault domains and stretched cluster
  vsphere/internal/helper/testhelper/testing.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_test.go
  website/docs/r/compute_cluster.html.markdown
Labels: documentation, size/m, provider

#2068 fix: explicitFailoverHost acc test failed after faultDomain acc test
  vsphere/resource_vsphere_compute_cluster.go
Labels: size/xs, provider

#2069 fix: guest os customization related vm e2e test
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: size/xs, provider

#2073 docs: update `FAQ.md`
  docs/FAQ.md
Labels: documentation, size/xs, provider
