Repository vmware/terraform-provider-vsphere, pull requests merged in 2023-08, with the labels that each got.

#1966 Fix for https://github.com/hashicorp/terraform-provider-vsphere/issue…
  vsphere/internal/helper/computeresource/compute_resource_helper.go
  vsphere/internal/helper/envbrowse/environment_browser_helper.go
  vsphere/internal/helper/resourcepool/resource_pool_helper.go
  vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/xs, provider

#1971 chore: CI add small script to find potential regressions from previous day
  .github/workflows/acceptance-tests.yaml
  scripts/compare-testlogs.js
Labels: size/m, provider

#1974 Revert "Fix for https://github.com/hashicorp/terraform-provider-vsphere/issue…"
  vsphere/internal/helper/computeresource/compute_resource_helper.go
  vsphere/internal/helper/envbrowse/environment_browser_helper.go
  vsphere/internal/helper/resourcepool/resource_pool_helper.go
  vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/xs, provider

#1975 chore(ci): check for panic in logfile
  .github/workflows/acceptance-tests.yaml
Labels: size/xs, provider

#1980 Fix acceptance tests workflow
  .github/workflows/acceptance-tests.yaml
Labels: size/s, provider

#1985 Restore regression check
  .github/workflows/acceptance-tests.yaml
  scripts/compare-testlogs.js
Labels: size/s, provider

#1986 chore(ci): summarize test output
  .github/workflows/acceptance-tests.yaml
  scripts/compare-testlogs.js
  scripts/summarize-testlog.js
Labels: size/s, provider, chore, github/actions

#1989 chore(ci): ignore workflow status in log download
  .github/workflows/acceptance-tests.yaml
Labels: size/xs, provider

#1993 chore(docs): Update contributing documentation
  acctests/README.md
  docs/CONTRIBUTING.md
Labels: documentation, size/s, provider

#1996 Bugfix addressing issue-1809.
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/m, provider

#1998 chore(ci): Update lockfiles
  acctests/equinix/.terraform.lock.hcl
  acctests/vsphere/base/.terraform.lock.hcl
  acctests/vsphere/testrun/.terraform.lock.hcl
Labels: size/m

#2001 chore(docs): Acceptance tests update
  acctests/README.md
Labels: documentation, size/xs
