Repository vmware/terraform-provider-vsphere, pull requests merged in 2023-12, with the labels that each got.

#2083 [Fix 2074] Fixing incorrect validation path in GOSC schema
  vsphere/internal/helper/guestoscustomizations/customizations_helper.go
Labels: size/xs, provider

#2085 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation

#2096 chore(ci): fix failing `actions/labeler`
  .github/labeler-pull-request-triage.yml
  .github/labeler-pull-requests.yml
  .github/workflows/pull-request.yml
Labels: chore
