Repository vmware/terraform-provider-vsphere, pull requests merged in 2023-04, with the labels that each got.

#1880 chore: Begin overhauling provider acceptance test setup
  acctests/README.md
  acctests/equinix/devrc.tpl
  acctests/equinix/main.tf
  acctests/equinix/vcsa_deploy.json
  acctests/equinix/versions.tf
  acctests/vsphere/deploy-nested-esxi.tf
  acctests/vsphere/devrc.tpl
  acctests/vsphere/for-acceptance-tests.tf
  acctests/vsphere/main.tf
  acctests/vsphere/nested-esxi-template.tf
  acctests/vsphere/output.tf
  acctests/vsphere/versions.tf
  vsphere/data_source_vsphere_content_library_item_test.go
  vsphere/data_source_vsphere_content_library_test.go
  vsphere/data_source_vsphere_host_thumbprint_test.go
  vsphere/data_source_vsphere_resource_pool_test.go
  vsphere/internal/helper/testhelper/testing.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_datastore_cluster_vm_anti_affinity_rule_test.go
  vsphere/resource_vsphere_host_port_group_test.go
  vsphere/resource_vsphere_host_virtual_switch_test.go
  vsphere/resource_vsphere_nas_datastore_test.go
  vsphere/resource_vsphere_storage_drs_vm_override_test.go
  vsphere/resource_vsphere_vapp_container_test.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: documentation, size/xl, provider

#1864 fix: remove vsan reconfigure timeout
  vsphere/internal/helper/vsanclient/vsan_client_helper.go
Labels: size/xs, provider, area/clustering

#1884 docs: update `r/vsphere_host`
  website/docs/r/host.html.markdown
Labels: documentation, size/xs

#1866 fix: `r/vsphere_file` provider crash
  vsphere/resource_vsphere_file.go
  vsphere/resource_vsphere_file_test.go
Labels: bug, size/m, provider, area/storage
