Repository vmware/terraform-provider-vsphere, pull requests merged in 2023-02, with the labels that each got.

#1827 docs: vm ovf local deploy example usage
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, size/xs

#1817 fix: update to `datastore_id` applies to `r/virtual_machine` disk sub-resources
  .gitignore
  main.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: bug, size/m, provider, area/vm

#1822 feat: add support for import of `r/vsphere_role`
  vsphere/data_source_vsphere_role_test.go
  vsphere/resource_vsphere_role.go
  vsphere/resource_vsphere_role_test.go
  website/docs/r/vsphere_role.html.markdown
Labels: documentation, size/l, provider, area/iam

#1835 Robustly check nil for all vsan data
  vsphere/resource_vsphere_compute_cluster.go
Labels: size/s, provider
