Repository vmware/terraform-provider-vsphere, pull requests merged in 2023-01, with the labels that each got.

#1808 fix: revert sha1 linting update
  vsphere/config.go
Labels: bug, size/xs, provider

#1812 chore(deps): bump Go to 1.19
  .go-version
  README.md
  scripts/config_builder.sh
Labels: dependencies, chore

#1811 chore: Remove CircleCI
  .circleci/config.yml
  .github/labeler-pull-request-triage.yml
  vsphere/data_source_vsphere_host.go
Labels: chore, github/repo

#1815 .github/workflows: Use actions/setup-go go-version-file input
  .github/workflows/release.yml
  .github/workflows/unit_tests.yaml
Labels: size/xs, provider, chore, github/actions

#1823 docs: fix broken links
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, waiting-response, size/xs
