Repository vmware/terraform-provider-vsphere, pull requests merged in 2024-10, with the labels that each got.

#2266 fix: `r/vsphere_host` thumbprint error
  CHANGELOG.md
  vsphere/data_source_vsphere_host_thumbprint.go
  vsphere/resource_vsphere_host.go
  website/docs/d/host_thumbprint.html.markdown
  website/docs/r/host.html.markdown
Labels: bug, documentation, provider, needs-review, area/host

#2272 docs: `r/vsphere_virtual_machine` updated disks info
  CHANGELOG.md
  website/docs/r/host.html.markdown
  website/docs/r/resource_pool.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation

#2285 Fix typo in virtual_machine.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation

#2274 feat: add datastore information under datastore cluster
  vsphere/data_source_vsphere_datastore_cluster.go
  vsphere/data_source_vsphere_datastore_cluster_test.go
  website/docs/d/datastore_cluster.html.markdown
Labels: enhancement, documentation, provider, needs-review, area/storage, area/clustering

#2273 feat: add in-cluster datastores in `d/datastore_stats`
  vsphere/data_source_vsphere_datastore_stats.go
  vsphere/data_source_vsphere_datastore_stats_test.go
Labels: enhancement, provider, needs-review, area/storage, area/clustering

#2276 feat: add `virtual_machines` list in `d/datacenter`
  vsphere/data_source_vsphere_datacenter.go
  vsphere/data_source_vsphere_datacenter_test.go
  website/docs/d/datacenter.html.markdown
Labels: enhancement, documentation, provider

#2281 feat: d/vsphere_network add support for network_type
  CHANGELOG.md
  vsphere/data_source_vsphere_network.go
  vsphere/internal/helper/network/network_helper.go
  website/docs/d/network.html.markdown
Labels: enhancement, documentation, provider

#2279 feat: add support for vtpm
  CHANGELOG.md
  vsphere/data_source_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine.go
  website/docs/d/virtual_machine.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: enhancement, documentation, provider, needs-review

#2286 chore: release v2.10.0
  CHANGELOG.md
Labels: documentation, chore

#2289 chore(deps): update `golang/go` to v1.22.8
  .go-version
  CHANGELOG.md
  README.md
  go.mod
Labels: documentation, dependencies, provider, chore, needs-review

#2294 docs: update landing docs
  README.md
  website/docs/index.html.markdown
Labels: documentation, needs-review
