Repository vmware/terraform-provider-vsphere, pull requests merged in 2024-09, with the labels that each got.

#2254 chore: release v2.9.0
  CHANGELOG.md
Labels: documentation, chore, needs-review

#2255 fix: `r/resouce_pool` scaleable shares
  CHANGELOG.md
  vsphere/resource_vsphere_resource_pool.go
Labels: bug, provider, needs-review

#2256 docs: update `network_interface`
  CHANGELOG.md
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, needs-review

#2257 docs: updated import `hosts`, `clusters`, and `virtual_machine`
  CHANGELOG.md
  website/docs/r/compute_cluster.html.markdown
  website/docs/r/host.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, needs-review

#2260 fix: add vm to existing vm group
  CHANGELOG.md
  vsphere/resource_vsphere_compute_cluster_vm_group.go
  website/docs/r/compute_cluster_vm_group.html.markdown
Labels: provider, area/clustering

#2261 feat: add validation for `category_id` in `r/vsphere_tag`
  CHANGELOG.md
  vsphere/resource_vsphere_tag.go
Labels: provider, area/tagging

#2263 fix: `r/vsphere_tag_category` cardinality
  CHANGELOG.md
  vsphere/resource_vsphere_tag_category.go
Labels: bug, provider

#2264 docs: updated `resource_pool` for standalone hosts
  CHANGELOG.md
  website/docs/r/resource_pool.html.markdown
Labels: documentation
