Repository vmware/terraform-provider-vsphere, pull requests merged in 2024-04, with the labels that each got.

#2175 chore(ci): codeql-analysis with go1.21+
  .github/workflows/codeql-analysis.yml
Labels: chore, github/actions

#2179 feat: Add support for vSphere Workload Management
  vsphere/provider.go
  vsphere/resource_vsphere_supervisor.go
  vsphere/resource_vsphere_supervisor_test.go
  vsphere/resource_vsphere_virtual_machine_class.go
  vsphere/resource_vsphere_virtual_machine_class_test.go
  website/docs/r/supervisor.html.markdown
  website/docs/r/virtual_machine_class.html.markdown
Labels: enhancement

#2182 docs: guest customizations anchor link
  website/docs/d/guest_os_customization.html.markdown
  website/docs/r/guest_os_customization.html.markdown
Labels: documentation

#2183 docs: update `vsphere_folder`
  website/docs/d/folder.html.markdown
  website/docs/r/folder.html.markdown
Labels: documentation

#2184 chore: update to sha256 for session file
  vsphere/config.go
Labels: dependencies, chore

#2186 chore(ci): codeql-analysis with go1.21+
  .github/workflows/codeql-analysis.yml
Labels: chore

#2188 chore(ci): codeql-analysis with go1.21+
  .github/workflows/codeql-analysis.yml
Labels: chore
