Repository vmware/terraform-provider-vsphere, pull requests merged in 2024-02, with the labels that each got.

#1762 fix: import of `r/vsphere_virtual_disk` imports the wrong `vmdk_path`
  vsphere/resource_vsphere_virtual_disk.go
  website/docs/r/virtual_disk.html.markdown
Labels: bug, documentation, size/xs, provider, area/storage

#2048 feat: add data source vgpu profiles
  vsphere/data_source_vsphere_host_vgpu_profile.go
  vsphere/provider.go
  website/docs/d/host_vgpu_profile.html.markdown
Labels: documentation, new-data-source, size/l, provider

#1896 feat: add disk stats for datastore
  vsphere/data_source_vsphere_datastore.go
  vsphere/data_source_vsphere_datastore_stats.go
  vsphere/data_source_vsphere_datastore_stats_test.go
  vsphere/data_source_vsphere_datastore_test.go
  vsphere/provider.go
  website/docs/d/datastore.html.markdown
  website/docs/d/datastore_stats.html .markdown
Labels: enhancement, size/l, provider, area/storage

#2133 fix: support for sr-iov passthrough virtual machine network adapters
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: area/vm, area/networking

#2139 chore(deps): bump go from 1.18 to 1.22
  .go-version
  README.md
  go.mod
  go.sum
  vsphere/distributed_virtual_switch_helper.go
  vsphere/helper_test.go
  vsphere/internal/helper/clustercomputeresource/cluster_compute_resource_helper.go
  vsphere/internal/helper/computeresource/compute_resource_helper.go
  vsphere/internal/helper/datastore/datastore_helper.go
  vsphere/internal/helper/folder/folder_helper.go
  vsphere/internal/helper/hostsystem/host_system_helper.go
  vsphere/internal/helper/resourcepool/resource_pool_helper.go
  vsphere/internal/helper/storagepod/storage_pod_helper.go
  vsphere/internal/helper/vappcontainer/vappcontainer_helper.go
  vsphere/internal/helper/viapi/vim_helper.go
  vsphere/internal/helper/virtualdisk/virtual_disk_helper.go
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/internal/helper/vsanclient/vsan_client_helper.go
  vsphere/internal/helper/vsansystem/vsansystem_helper.go
  vsphere/resource_vsphere_distributed_port_group.go
  vsphere/resource_vsphere_distributed_virtual_switch.go
  vsphere/resource_vsphere_file.go
  vsphere/resource_vsphere_folder.go
  vsphere/resource_vsphere_folder_test.go
  vsphere/resource_vsphere_host.go
  vsphere/resource_vsphere_virtual_disk.go
  vsphere/resource_vsphere_virtual_machine_snapshot.go
Labels: dependencies, chore
