Repository vmware/terraform-provider-vsphere, pull requests merged in 2024-05, with the labels that each got.

#2061 fix: allow `datastore_cluster` for content library clones
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/xs, provider

#2181 feat: add `domain_ou` support for windows customization
  vsphere/data_source_vsphere_guest_os_customization.go
  vsphere/internal/helper/guestoscustomizations/customizations_helper.go
  vsphere/resource_vsphere_guest_os_customization.go
  vsphere/resource_vsphere_virtual_machine.go
  website/docs/r/virtual_machine.html.markdown
Labels: enhancement, documentation, provider, vsphere/v8

#2192 chore(release): v2.8.0
  CHANGELOG.md
Labels: documentation, chore

#2194 Revert "bugfix: Remove default values for ept_rvi_mode and hv_mode"
  CHANGELOG.md
  vsphere/virtual_machine_config_structure.go
Labels: documentation, provider, needs-review

#2198 feat: add `instance_uuid` to `d/virtual_machine`
  CHANGELOG.md
  vsphere/data_source_vsphere_virtual_machine.go
  vsphere/data_source_vsphere_virtual_machine_test.go
  website/docs/d/virtual_machine.html.markdown
Labels: enhancement, documentation, provider, area/vm

#2207 docs: use correct vm template's firmware in local OVF example
  website/docs/d/ovf_vm_template.html.markdown
Labels: documentation
