Repository vmware/terraform-provider-vsphere, pull requests merged in 2024-12, with the labels that each got.

#2306 fix: add 8.0.3 to dvsVersions
  CHANGELOG.md
  vsphere/distributed_virtual_switch_helper.go
  vsphere/distributed_virtual_switch_structure.go
Labels: bug, documentation, provider, needs-review

#2310 Extra notes on automated testing
  acctests/equinix/README.md
  acctests/vsphere/README.md
Labels: documentation, provider, needs-review

#2311 chore: update `.gitignore`
  .gitignore
  acctests/equinix/.terraform.lock.hcl
  acctests/vsphere/base/.terraform.lock.hcl
  acctests/vsphere/testrun/.terraform.lock.hcl
Labels: provider, chore, needs-review

#2313 FIX: website doc typos
  website/docs/r/compute_cluster_vm_host_rule.html.markdown
  website/docs/r/drs_vm_override.html.markdown
  website/docs/r/host_virtual_switch.html.markdown
  website/docs/r/virtual_machine.html.markdown
Labels: documentation, needs-review
