Repository vmware/terraform-provider-vsphere, pull requests merged in 2024-08, with the labels that each got.

#2244 feat: allow resizing of virtual disks
  vsphere/resource_vsphere_virtual_disk.go
  vsphere/resource_vsphere_virtual_disk_test.go
  website/docs/r/virtual_disk.html.markdown
Labels: documentation, provider, needs-review

#2246 chore: release v2.8.3
  CHANGELOG.md
Labels: chore

#2243 PSS-277: Bump hashicorp/ghaction-terraform-provider-release/.github/w…
  .github/workflows/release.yml
Labels: chore, needs-review, github-actions

#2232 feat: add support for ntpd service on `r/vsphere_host`
  CHANGELOG.md
  vsphere/resource_vsphere_host.go
  vsphere/resource_vsphere_host_test.go
  website/docs/r/host.html.markdown
Labels: enhancement, documentation, provider, needs-review, area/host

#2247 chore(deps): bump go from 1.22 to 1.22.6
  .go-version
  CHANGELOG.md
  README.md
  go.mod
Labels: documentation, dependencies, provider, chore, needs-review
