Repository vmware/terraform-provider-vsphere, pull requests merged in 2024-01, with the labels that each got.

#2093 fix: add `memory_reservation_locked_to_max` property to `r/vsphere_virtual_macine` schema for sr-iov
  vsphere/data_source_vsphere_virtual_machine_test.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/virtual_machine_config_structure.go
Labels: bug, area/vm, area/networking

#2112 fix(ci): pull request labels
  .github/workflows/pull-request.yml
Labels: bug, github/actions

#2105 docs: update `INSTALL.md`
  docs/INSTALL.md
Labels: documentation

#2120 fix: set `sync_time_with_host` to default to `true`
  vsphere/virtual_machine_config_structure.go
  website/docs/r/virtual_machine.html.markdown
Labels: bug

#2118 fix: add vm folder when querying for vm
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: bug
