Repository vmware/terraform-provider-vsphere, pull requests merged in 2024-03, with the labels that each got.

#2144 chore(release): v2.7.0
  CHANGELOG.md
Labels: chore

#2145 chore(ci): revert `actions/upload-artifact`
  .github/workflows/acceptance-tests.yaml
  .github/workflows/release.yml
Labels: chore, github/actions

#2121 fix: select guest ips using MacAddress
  vsphere/virtual_machine_guest_structure.go
Labels: bug

#2143 feat: add support for vlcm (offline software depots, cluster images)
  CHANGELOG.md
  vsphere/data_source_vsphere_host_base_images.go
  vsphere/internal/helper/testhelper/testing.go
  vsphere/provider.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_test.go
  vsphere/resource_vsphere_offline_software_depot.go
  vsphere/resource_vsphere_offline_software_depot_test.go
  website/docs/d/host_base_images.html.markdown
  website/docs/r/compute_cluster.html.markdown
  website/docs/r/offline_software_depot.html.markdown
Labels: enhancement, upstream/govmomi
