Repository vmware/terraform-provider-vsphere, pull requests merged in 2025-07, with the labels that each got.

#2553 docs(virtual_machine): fix broken link to “Specifying the Root Resource Pool”
  docs/resources/virtual_machine.md
Labels: documentation, size/xs, size/xl, needs-review

#2561 fix: update static mac when reconfiguring vm
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
Labels: size/xs, provider, needs-review

#2560 fix: server fault when cloning VM on DRS-enabled cluster
  vsphere/internal/helper/storagepod/storage_pod_helper.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: size/xs, provider, needs-review

#2563 chore(release): v2.14.1
  CHANGELOG.md
Labels: documentation, size/xs, needs-review

#2566 fix: doc typo for virtual_disk
  docs/resources/virtual_disk.md
Labels: documentation, size/xs, needs-review

#2567 feat: support deploying OVA without specifying host_system_id
  docs/resources/virtual_machine.md
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: documentation, size/s, provider, needs-review
