Repository vmware/terraform-provider-vsphere, pull requests merged in 2025-05, with the labels that each got.

#2459 docs: update folder documentation
  docs/data-sources/folder.md
  docs/resources/folder.md
Labels: documentation

#2399 chore: remove unused scripts
  scripts/compare-testlogs.js
  scripts/summarize-testlog.js
Labels: chore

#2456 chore(gh): update tests workflow
  .github/workflows/test.yml
Labels: chore, github-actions

#2396 chore(xfer): remove greeting workflow
  .github/issue_greeting_template.md
  .github/workflows/issue_greeting.yml
Labels: chore, github-actions

#2405 chore(xfer): remove codeql workflow
  .github/workflows/codeql-analysis.yml
Labels: chore, github-actions

#2410 chore(xfer): update codeowners
  CODEOWNERS
Labels: chore

#2398 chore(xfer): update code-of-conduct
  CODE_OF_CONDUCT.md
  docs/CODE_OF_CONDUCT.md
Labels: chore

#2400 chore(xfer): update issue labels workflow
  .github/labeler-issue-triage.yml
  .github/labeler-issues.yml
  .github/workflows/issue-opened.yml
Labels: chore, github-actions

#2404 chore(xfer): update pull request labels workflow
  .github/labeler-pull-requests.yml
  .github/workflows/pull-requests.yml
Labels: chore

#2397 chore(xfer): update issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
Labels: chore, needs-review

#2407 chore(xfer): update pull request template
  .github/pull_request_template.md
Labels: documentation, chore, needs-review

#2402 chore(xfer): add notice
  NOTICE
Labels: chore

#2406 chore(xfer): update registry manifest
  terraform-registry-manifest.json
Labels: chore, needs-review

#2409 chore(xfer): update project-level documentation
  .github/tf.png
  README.md
  docs/build.md
  docs/faq.md
  docs/images/icon-color.svg
  docs/images/icon-white.svg
  docs/install.md
  docs/issues.md
  docs/pull_requests.md
  docs/support.md
Labels: documentation, chore, needs-review

#2412 chore(xfer): update license
  LICENSE
Labels: chore, needs-review

#2411 chore(xfer): remove metadata
  .release/release-metadata.hcl
  META.d/_summary.yaml
  META.d/links.yaml
Labels: chore, needs-review

#2463 chore(gh): update golangci-lint workflow
  .github/workflows/golangci-lint.yml
  .golangci.yml
Labels: chore, github-actions

#2465 chore(gh): update pull request workflow
  .github/workflows/pull-requests.yml
Labels: chore, github-actions

#2466 chore(gh): update issue workflow
  .github/workflows/remove-issue-label.yml
Labels: chore, github-actions

#2467 chore(gh): update milestone closed workflow
  .github/workflows/milestone-closed.yml
Labels: chore, github-actions

#2468 chore(gh): update comment workflow
  .github/workflows/issue-comment-created.yml
Labels: chore, github-actions

#2419 fix: ineffectual assignment
  .golangci.yml
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: dependencies, technical-debt, provider, chore, needs-review, refactor

#2436 refactor: license resource and data source
  go.mod
  vsphere/data_source_vsphere_license.go
  vsphere/internal/helper/license/license_helper.go
  vsphere/resource_vsphere_license.go
  vsphere/resource_vsphere_license_test.go
Labels: dependencies, technical-debt, provider, chore, needs-review, refactor

#2415 fix: revive var-naming
  vsphere/data_source_vsphere_dynamic.go
  vsphere/data_source_vsphere_dynamic_test.go
  vsphere/data_source_vsphere_role_test.go
  vsphere/internal/helper/guestoscustomizations/customizations_helper.go
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
  vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/provider.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_compute_cluster_vm_group.go
  vsphere/resource_vsphere_distributed_virtual_switch_pvlan_mapping_test.go
  vsphere/resource_vsphere_offline_software_depot.go
  vsphere/resource_vsphere_role.go
  vsphere/resource_vsphere_role_test.go
  vsphere/resource_vsphere_supervisor.go
  vsphere/resource_vsphere_supervisor_test.go
  vsphere/resource_vsphere_vapp_container_test.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_class.go
  vsphere/resource_vsphere_virtual_machine_class_test.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/resource_vsphere_vm_storage_policy.go
  vsphere/resource_vsphere_vnic.go
Labels: technical-debt, provider, needs-review, refactor

#2477 chore: update release history
  CHANGELOG.md
Labels: documentation, chore, needs-review

#2478 docs: update docs index
  docs/index.md
Labels: documentation, needs-review

#2480 docs: clarify `disk_provisioning` options
  CHANGELOG.md
  docs/data-sources/ovf_vm_template.md
  docs/resources/virtual_machine.md
Labels: documentation, needs-review

#2483 chore: update `.golangci.yml`
  .golangci.yml
Labels: chore, needs-review

#2481 chore: fix staticcheck ST1005
  .golangci.yml
  vsphere/config.go
  vsphere/internal/helper/contentlibrary/content_library_helper.go
  vsphere/internal/helper/customattribute/custom_attributes_helper.go
  vsphere/internal/virtualdevice/virtual_machine_cdrom_subresource.go
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/resource_vsphere_virtual_disk.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_snapshot.go
  vsphere/resource_vsphere_vmfs_datastore.go
  vsphere/tags_helper.go
Labels: technical-debt, provider, needs-review

#2487 chore: rename makefile
  Makefile
Labels: chore, needs-review

#2485 chore(release): v2.13.0
  CHANGELOG.md
Labels: documentation, chore

#2460 feat: add `parent_resource_pool_id` to `d/resource_pool`
  docs/data-sources/resource_pool.md
  vsphere/data_source_vsphere_resource_pool.go
  vsphere/data_source_vsphere_resource_pool_test.go
  vsphere/internal/helper/resourcepool/resource_pool_helper.go
Labels: enhancement, documentation, provider

#2488 fix: staticcheck S1005
  .golangci.yml
  vsphere/resource_vsphere_offline_software_depot_test.go
Labels: technical-debt, provider, chore, needs-review

#2489 fix: staticcheck S1040
  .golangci.yml
  vsphere/internal/virtualdevice/virtual_machine_device_subresource.go
Labels: technical-debt, provider, chore

#2490 fix: staticcheck S1017
  .golangci.yml
  vsphere/resource_vsphere_virtual_machine.go
Labels: technical-debt, provider, chore, needs-review

#2491 fix: staticcheck S1009
  .golangci.yml
  vsphere/resource_vsphere_compute_cluster.go
Labels: technical-debt, provider, chore, needs-review

#2492 fix: staticcheck QF1012
  .golangci.yml
  vsphere/data_source_vsphere_host_vgpu_profile.go
Labels: technical-debt, provider, chore, needs-review

#2493 fix: staticcheck QF1008
  .golangci.yml
  vsphere/resource_vsphere_file.go
Labels: technical-debt, provider, chore, needs-review

#2500 chore: add a foundation for running acceptance tests on a bare vSphere setup
  acctests/equinix/README.md
  acctests/equinix/devrc.tpl
  acctests/equinix/main.tf
  acctests/equinix/vcsa_deploy.json
  acctests/equinix/versions.tf
  tests/README.md
  tests/main.tf
  tests/run_tests.sh
  tests/setup_env_vars.sh
  tests/variables.tf
  vsphere/internal/helper/testhelper/constants.go
Labels: documentation, provider, needs-review

#2501 chore: remove legacy tests
  acctests/README.md
  acctests/vsphere/README.md
  acctests/vsphere/base/devrc.tpl
  acctests/vsphere/base/main.tf
  acctests/vsphere/base/output.tf
  acctests/vsphere/base/versions.tf
  acctests/vsphere/testrun/deploy-nested-esxi.tf
  acctests/vsphere/testrun/deploy-nfs.tf
  acctests/vsphere/testrun/devrc.tpl
  acctests/vsphere/testrun/for-acceptance-tests.tf
  acctests/vsphere/testrun/main.tf
  acctests/vsphere/testrun/nested-esxi-template.tf
  acctests/vsphere/testrun/nfs-cloud-config.yaml.tpl
  acctests/vsphere/testrun/output.tf
  acctests/vsphere/testrun/ubuntu-template.tf
  acctests/vsphere/testrun/versions.tf
  tests/README.md
Labels: documentation, chore, tests

#2502 chore: format tests
  tests/main.tf
  tests/variables.tf
Labels: chore, needs-review

#2505 fix: staticcheck SA4006
  .golangci.yml
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: technical-debt, provider, needs-review

#2504 fix: staticcheck QF1005
  .golangci.yml
  vsphere/internal/helper/structure/structure_helper.go
Labels: technical-debt, provider, needs-review

#2503 fix: rename unused parameters
  .golangci.yml
  vsphere/event_helper.go
  vsphere/internal/administrationroles/vsphere_permission_subresource.go
  vsphere/internal/helper/structure/structure_helper.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_content_library_item_test.go
  vsphere/resource_vsphere_host.go
  vsphere/resource_vsphere_virtual_disk.go
  vsphere/resource_vsphere_virtual_machine_test.go
  vsphere/resource_vsphere_vnic.go
  vsphere/virtual_machine_config_structure.go
Labels: technical-debt, provider, needs-review

#2506 chore: `gosec` ignore `crypto/sha1`
  .golangci.yml
  vsphere/data_source_vsphere_host_thumbprint.go
  vsphere/resource_vsphere_host.go
Labels: technical-debt, provider, chore, needs-review

#2510 fix: address G107 gosec warnings in HTTP requests
  .golangci.yml
  vsphere/internal/helper/contentlibrary/content_library_helper.go
  vsphere/resource_vsphere_content_library_item_test.go
Labels: technical-debt, provider, needs-review

#2518 chore: update codeowners
  CODEOWNERS
Labels: chore, needs-review

#2516 chore: remove unused test function
  .golangci.yml
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: technical-debt, provider, chore, needs-review, tests

#2517 chore: sort `ResourcesMap` and `DataSourcesMap`
  vsphere/provider.go
Labels: technical-debt, provider, chore, needs-review

#2515 chore: remove legacy min versions
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: technical-debt, provider, chore, needs-review

#2507 fix: gosec g402
  .golangci.yml
  vsphere/data_source_vsphere_host_thumbprint.go
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
  vsphere/resource_vsphere_host.go
Labels: technical-debt, provider

#2482 refactor: use of deprecated `GetOkExists`
  vsphere/distributed_virtual_port_setting_structure.go
  vsphere/host_network_policy_structure.go
  vsphere/internal/helper/structure/structure_helper.go
Labels: technical-debt, provider, needs-review, refactor

#2525 refactor: stabilize and enable data source tests
  docs/resources/datastore_cluster.md
  tests/run_tests.sh
  vsphere/data_source_vsphere_compute_cluster_host_group_test.go
  vsphere/data_source_vsphere_compute_cluster_test.go
  vsphere/data_source_vsphere_datacenter_test.go
  vsphere/data_source_vsphere_datastore_cluster_test.go
  vsphere/data_source_vsphere_datastore_stats_test.go
  vsphere/data_source_vsphere_distributed_virtual_switch_test.go
  vsphere/data_source_vsphere_dynamic_test.go
  vsphere/data_source_vsphere_guest_os_customization_test.go
  vsphere/data_source_vsphere_host_test.go
  vsphere/data_source_vsphere_host_thumbprint_test.go
  vsphere/data_source_vsphere_network_test.go
  vsphere/data_source_vsphere_resource_pool_test.go
  vsphere/data_source_vsphere_role_test.go
  vsphere/data_source_vsphere_tag_test.go
  vsphere/data_source_vsphere_vapp_container_test.go
  vsphere/data_source_vsphere_virtual_machine_test.go
  vsphere/data_source_vsphere_vmfs_disks_test.go
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/resource_vsphere_datastore_cluster.go
  vsphere/resource_vsphere_resource_pool.go
Labels: documentation, provider, needs-review

#2530 refactor: exported name starts with package
  vsphere/data_source_vsphere_network.go
  vsphere/internal/helper/network/network_helper.go
Labels: technical-debt, provider, needs-review, refactor

#2526 fix: error message casing
  vsphere/data_source_vsphere_vmfs_disks_test.go
  vsphere/helper_test.go
  vsphere/resource_vsphere_content_library_item_test.go
  vsphere/resource_vsphere_content_library_test.go
  vsphere/resource_vsphere_file_test.go
  vsphere/resource_vsphere_host_test.go
  vsphere/resource_vsphere_license_test.go
  vsphere/resource_vsphere_virtual_disk_test.go
  vsphere/resource_vsphere_virtual_machine_snapshot_test.go
Labels: technical-debt, provider, needs-review

#2529 refactor: direct comparison of errors
  vsphere/event_helper.go
  vsphere/internal/helper/storagepod/storage_pod_helper.go
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
Labels: technical-debt, provider, needs-review, refactor

#2528 chore: remove redundant type conversions
  vsphere/data_source_vsphere_virtual_machine.go
  vsphere/internal/helper/envbrowse/environment_browser_helper.go
  vsphere/internal/helper/structure/structure_helper.go
  vsphere/internal/helper/virtualdisk/virtual_disk_helper.go
  vsphere/resource_vsphere_compute_cluster_host_group_test.go
  vsphere/resource_vsphere_compute_cluster_vm_affinity_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_anti_affinity_rule_test.go
  vsphere/resource_vsphere_compute_cluster_vm_group_test.go
  vsphere/resource_vsphere_datastore_cluster_vm_anti_affinity_rule_test.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_migrate.go
  vsphere/resource_vsphere_virtual_machine_migrate_test.go
Labels: technical-debt, provider, chore, needs-review

#2524 refactor: remove legacy state migration
  vsphere/host_port_group_structure.go
  vsphere/resource_vsphere_content_library_item.go
  vsphere/resource_vsphere_content_library_item_migrate.go
  vsphere/resource_vsphere_folder.go
  vsphere/resource_vsphere_folder_migrate.go
  vsphere/resource_vsphere_folder_migrate_test.go
  vsphere/resource_vsphere_virtual_machine.go
  vsphere/resource_vsphere_virtual_machine_migrate.go
  vsphere/resource_vsphere_virtual_machine_migrate_test.go
  vsphere/virtual_machine_config_structure.go
Labels: technical-debt, provider, needs-review, refactor

#2531 refactor: enable r/vsphere_virtual_machine tests
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: provider, needs-review

#2527 refactor: replace type assertion on errors
  vsphere/data_source_vsphere_network.go
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/resource_vsphere_datacenter.go
  vsphere/resource_vsphere_datacenter_test.go
  vsphere/resource_vsphere_file.go
  vsphere/resource_vsphere_file_test.go
  vsphere/resource_vsphere_virtual_machine.go
Labels: technical-debt, provider, needs-review, refactor

#2534 refactor: use nil slice declaration
  vsphere/data_source_vsphere_datacenter.go
  vsphere/data_source_vsphere_datastore_cluster.go
  vsphere/data_source_vsphere_host_pci_device.go
  vsphere/internal/helper/contentlibrary/content_library_helper.go
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/tags_helper.go
Labels: size/xs, technical-debt, provider, needs-review, refactor
