Repository vmware/terraform-provider-vsphere, pull requests merged in 2025-04, with the labels that each got.

#2373 chore(gh): update to goreleaser v2
  .goreleaser.yml
Labels: chore, needs-review, github/actions

#2375 docs: update `docscheck.sh`
  docs/resources/compute_cluster_host_group.md
  docs/resources/compute_cluster_vm_host_rule.md
  docs/resources/custom_attribute.md
  docs/resources/datastore_cluster.md
  docs/resources/license.md
  docs/resources/nas_datastore.md
  docs/resources/vmfs_datastore.md
  scripts/docscheck.sh
Labels: documentation, chore, needs-review

#2376 chore(gh): add golangci-lint workflow
  .github/workflows/golangci-lint.yml
  .golangci.yml
Labels: chore, github/actions

#2384 chore(release): v2.12.0
  CHANGELOG.md
Labels: chore

#2390 chore(gh): add docs workflow
  .github/workflows/docs.yml
  GNUmakefile
  scripts/docscheck.sh
Labels: chore, github/actions

#2392 chore(gh): update stale workflow
  .github/workflows/stale.yml
Labels: chore, github/actions

#2391 chore(gh): update lock workflow
  .github/workflows/lock.yml
Labels: chore, github/actions

#2388 feat: add `DiffSuppressFunc` for `network_adapters` on r`/host_virtual_switch`
  vsphere/host_virtual_switch_structure.go
Labels: enhancement

#2395 chore: update `.gitignore`
  .gitignore
Labels: chore

#2420 fix: file format
  .golangci.yml
  main.go
  vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/resource_vsphere_guest_os_customization.go
  vsphere/resource_vsphere_offline_software_depot.go
  vsphere/resource_vsphere_virtual_machine_class.go
Labels: technical-debt, refactor

#2424 fix: exported type name stutter
  .golangci.yml
  vsphere/data_source_vsphere_network.go
  vsphere/internal/helper/network/network_helper.go
Labels: technical-debt, refactor

#2422 fix: error string punctuation
  .golangci.yml
  vsphere/resource_vsphere_compute_cluster.go
Labels: technical-debt, refactor

#2418 fix: unnecessary conversion
  .golangci.yml
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
Labels: technical-debt, refactor

#2431 refactor: simplify boolean comparisons in conditions
  vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go
  vsphere/virtual_machine_config_structure.go
Labels: technical-debt, refactor

#2435 docs: update license documentation
  docs/data-sources/license.md
  docs/resources/license.md
Labels: documentation

#2425 fix: staticcheck S1039
  .golangci.yml
  vsphere/resource_vsphere_virtual_machine_class_test.go
Labels: technical-debt, refactor

#2427 refactor: clean file paths
  vsphere/internal/helper/contentlibrary/content_library_helper.go
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
Labels: technical-debt, refactor

#2428 refactor: http get request handling
  vsphere/internal/helper/contentlibrary/content_library_helper.go
Labels: technical-debt, area/content-library, refactor

#2432 refactor: use switch expression over tagless switch
  vsphere/resource_vsphere_virtual_machine_test.go
Labels: technical-debt, refactor

#2433 refactor: use switch statement for os customization type
  vsphere/internal/helper/guestoscustomizations/customizations_helper.go
Labels: technical-debt, refactor

#2439 refactor: compute cluster drop else and outdent
  vsphere/resource_vsphere_compute_cluster.go
Labels: technical-debt, refactor

#2430 fix: avoid taking address of loop variables
  vsphere/host_data_store_system_helper.go
Labels: technical-debt, refactor

#2440 refactor: host base images drop else and outdent
  vsphere/data_source_vsphere_host_base_images.go
Labels: technical-debt, refactor

#2441 refactor: software depot drop else and outdent
  vsphere/resource_vsphere_offline_software_depot.go
  vsphere/resource_vsphere_offline_software_depot_test.go
Labels: technical-debt, refactor

#2434 refactor: simplify access to methods/fields via direct calls
  vsphere/config.go
  vsphere/internal/helper/ovfdeploy/ovf_helper.go
  vsphere/internal/helper/viapi/vim_helper.go
  vsphere/resource_vsphere_datacenter.go
  vsphere/resource_vsphere_file.go
Labels: technical-debt, refactor

#2429 fix: reconcile scale descendants shares
  vsphere/resource_vsphere_resource_pool.go
Labels: bug, needs-review

#2444 fix: prevent panic when both `ParentVApp` and `ResourcePool` are nil
  vsphere/resource_vsphere_virtual_machine.go
Labels: bug, crash

#2417 fix: redefinition of the built-in function
  .golangci.yml
  vsphere/data_source_vsphere_datastore_stats.go
  vsphere/distributed_virtual_port_setting_structure.go
  vsphere/helper_test.go
  vsphere/internal/helper/viapi/vim_helper.go
  vsphere/resource_vsphere_compute_cluster.go
  vsphere/virtual_machine_config_structure.go
Labels: technical-debt, refactor

#2450 chore(gh): update dependabot
  .github/dependabot.yml
Labels: chore, github-actions

#2449 chore(gh): remove equinix nightly workflow
  .github/workflows/acceptance-tests.yaml
Labels: chore, github-actions

#2421 fix: error not checked
  .golangci.yml
  vsphere/data_source_vsphere_datacenter.go
  vsphere/distributed_virtual_switch_helper.go
Labels: technical-debt, refactor

#2423 refactor: update `getHostThumbprint`
  .golangci.yml
  vsphere/resource_vsphere_host.go
Labels: technical-debt, refactor

#2437 refactor: file resource
  docs/resources/file.md
  vsphere/resource_vsphere_file.go
  vsphere/resource_vsphere_file_test.go
Labels: technical-debt, refactor

#2401 chore: update release history
  CHANGELOG.md
Labels: chore
