Repository vmware/terraform-provider-vsphere, pull requests merged in 2025-02, with the labels that each got.

#2326 feat: add support for ntp servers to r/vsphere_supervisor
  vsphere/resource_vsphere_supervisor.go
  website/docs/r/supervisor.html.markdown
Labels: documentation, provider, needs-review

#2329 chore: update session file format
  go.mod
  go.sum
  vsphere/config.go
Labels: dependencies, provider, chore, needs-review

#2333 chore(release): v2.11.1
  CHANGELOG.md
  website/docs/index.html.markdown
Labels: documentation, chore

#2334 chore(deps): bump github.com/hashicorp/yamux from v0.1.1 to v0.1.2
  go.mod
  go.sum
Labels: dependencies, provider, chore, needs-review
