Repository vmware/terraform-provider-vsphere, pull requests merged in 2025-08, with the labels that each got.

#2582 refactor: update hardware versions and validation
  docs/resources/virtual_machine.md
  vsphere/virtual_machine_config_structure.go
Labels: documentation, size/s, provider, needs-review, refactor

#2591 chore(release): v2.15.0
  CHANGELOG.md
Labels: documentation, size/xs, needs-review

#2592 chore(gh): generate release notes on release
  .github/workflows/release.yml
  scripts/release-notes.sh
Labels: size/m, chore, needs-review, github-actions

#2593 docs: update `README.md`
  README.md
Labels: documentation, needs-review

#2595 fix: return error when vMotion task fails
  vsphere/internal/helper/virtualmachine/virtual_machine_helper.go
Labels: size/xs, provider, needs-review
